import { createContext, useContext, useState, useEffect } from "react";

export const translations = {
  en: {
    dir: "ltr",
    // Sidebar
    hr_system: "HR System",
    emp_management: "Employee Management",
    hr_role: "HR Manager",
    // Nav
    nav_dashboard: "Dashboard",
    nav_employees: "Employees",
    nav_contracts: "Contracts",
    nav_expenses: "Expenses",
    nav_attendance: "Attendance",
    nav_leave_request: "Leave Request",
    nav_payroll: "Payroll",
    nav_documents: "Documents",
    nav_requests: "Requests",
    nav_revenue: "Revenue",
    nav_savings: "Safe",
    nav_users: "System Users",
    nav_settings: "Settings",
    // Employee page
    emp_title: "Employees",
    emp_total: (n) => `${n} employee${n !== 1 ? "s" : ""} total`,
    emp_stat_all: "All Employees",
    emp_stat_active: "Active",
    emp_stat_inactive: "Inactive",
    emp_stat_on_leave: "On Leave",
    emp_stat_suspended: "Suspended",
    emp_add_btn: "Add Employee",
    emp_search_placeholder: "Search by name or ID...",
    emp_modal_add: "Add Employee",
    emp_modal_edit: "Edit Employee",
    // Sections
    emp_section_photo: "Profile Photo",
    emp_upload_photo: "Upload Photo",
    emp_upload_hint: "JPG, PNG or GIF (MAX. 800x800px)",
    emp_section_personal: "Personal Information",
    emp_section_employment: "Employment Details",
    // Fields
    emp_full_name: "Full Name *",
    emp_phone: "Phone Number *",
    emp_email: "Email *",
    emp_gender: "Gender *",
    emp_male: "Male",
    emp_female: "Female",
    emp_city: "City",
    emp_position: "Position *",
    emp_department: "Department",
    emp_status: "Status",
    emp_contract_type: "Contract Type",
    emp_salary: "Base Salary (IQD)",
    emp_hire_date: "Hire Date",
    emp_bio: "Biography / Notes",
    emp_bio_placeholder: "Additional information about the employee...",
    emp_dob: "Date of Birth",
    emp_work_start: "Work Start Time",
    emp_work_end: "Work End Time",
    ph_dob: "Select date",
    ph_work_time: "e.g. 09:00",
    // Buttons
    btn_back: "Back",
    btn_cancel: "Cancel",
    btn_add: "Add",
    btn_update: "Update",
    btn_profile: "Profile",
    btn_edit: "Edit",
    btn_approve: "Approve",
    btn_reject: "Reject",
    btn_print: "Print",
    // Table columns
    col_id: "ID",
    col_employee: "Employee",
    col_email: "Email",
    col_position: "Position",
    col_department: "Department",
    col_salary: "Salary",
    col_status: "Status",
    col_actions: "Actions",
    col_date: "Date",
    col_type: "Type",
    col_notes: "Notes",
    // Placeholders
    ph_position: "Select position",
    ph_department: "Select department",
    ph_status: "Select status",
    ph_contract: "Select contract",
    ph_city: "Enter city",
    ph_name: "Enter full name",
    ph_phone: "Enter phone number",
    ph_email: "Enter email",
    ph_notes_opt: "Notes (optional)",
    // Language switcher
    lang_label: "Language",
    // Common
    lbl_all: "All",
    lbl_select_emp: "Select employee",
    lbl_required: "Please fill in all required fields",
    lbl_notes: "Notes",
    lbl_status: "Status",
    lbl_date: "Date",
    lbl_employee: "Employee *",
    lbl_department: "Department",
    lbl_no_data: "No data",
    dept_it: "IT",
    dept_finance: "Finance",
    dept_hr: "HR",
    dept_marketing: "Marketing",
    dept_operations: "Operations",
    dept_design: "Design",
    // Dashboard
    dash_title: "Dashboard",
    dash_sub: "Welcome back — here's what's happening today.",
    dash_active_emp: "Active Employees",
    dash_total: (n) => `Total: ${n}`,
    dash_present_today: "Present Today",
    dash_checked_in: "checked in",
    dash_pending_leaves: "Pending Leaves",
    dash_awaiting: "awaiting approval",
    dash_unpaid_payroll: "Unpaid Payroll",
    dash_emp_pending: "employees pending",
    dash_by_dept: "Employees by Department",
    dash_todays_att: "Today's Attendance",
    dash_recent_leaves: "Recent Leave Requests",
    dash_no_employees: "No employees",
    dash_no_leaves: "No leave requests",
    dash_today_hours: "Today's Work Hours",
    // Expenditure Analysis card
    ea_title: "Expenditure Analysis",
    ea_sub: "Safe goals over time",
    ea_weekly: "Weekly",
    ea_monthly: "Monthly",
    ea_yearly: "Yearly",
    ea_stat_total: "Total Claims",
    ea_stat_peak: "Peak Period",
    // Attendance
    att_title: "Attendance",
    att_sub: "Track daily check-ins",
    att_btn: "Record",
    att_present: "Present",
    att_absent: "Absent",
    att_late: "Late",
    att_on_leave: "On Leave",
    att_col_dept: "Dept",
    att_col_check_in: "Check In",
    att_col_check_out: "Check Out",
    att_col_total_hours: "Total Hours",
    att_col_overtime: "Overtime",
    att_modal_add: "Add Record",
    att_modal_edit: "Edit Record",
    att_fld_date: "Date *",
    att_fld_check_in: "Check In",
    att_fld_check_out: "Check Out",
    att_fld_status: "Status *",
    att_ph_notes: "Notes (optional)",
    att_btn_add: "Add Record",
    att_btn_update: "Update Record",
    // Face ID
    att_face_title_scan:     "🔍 Face ID — Attendance",
    att_face_title_register: "📷 Register Face ID",
    att_face_steps_scan:     ["Camera Ready", "Scanning Face", "Matching Employee", "Recording Attendance"],
    att_face_steps_reg:      ["Camera Ready", "Scanning Face", "Face Registered"],
    att_face_loading_init:   "Starting...",
    att_face_loading_api:    "Loading Face ID library...",
    att_face_loading_models: "Loading models (first time ~30s)...",
    att_face_cam_ready:      "Position your face in the frame",
    att_face_cam_retry:      (n) => `Retrying... (${n})`,
    att_face_detecting:      "Detecting face...",
    att_face_matching:       "Matching employee...",
    att_face_recording:      "Recording attendance...",
    att_face_err_lib:        "Face ID library failed to load.",
    att_face_err_models:     "Models failed to load.",
    att_face_err_camera:     "Camera not found. Please allow camera access.",
    att_face_err_scan:       "Scan error: ",
    att_face_err_reg:        "Registration failed: ",
    att_face_err_match:      "Match failed: ",
    att_no_employee_found:   "No employee found with name",
    att_face_check_in:       "✅ Checked In Successfully",
    att_face_check_out:      "🔵 Checked Out Successfully",
    att_face_already:        "⚠️ Already recorded for today",
    att_face_days:           "Days Present",
    att_face_reg_ok:         "Face ID registered successfully!",
    att_face_done:           "Done ✓",
    att_face_close:          "Close",
    att_face_sel_label:      "Select Employee",
    att_face_sel_ph:         "Choose employee...",
    att_face_scan_btn:       "📷 Scan & Register Face ID",
    att_face_toast:          (name) => `Face ID registered for ${name}`,
    att_face_warning:        "Position your face directly at the camera in good lighting.",
    att_face_btn_reg:        "Register",
    att_face_btn_scan:       "Face ID",
    att_toast_add:           "Attendance added successfully",
    att_toast_update:        "Attendance updated successfully",
    att_toast_delete:        "Record deleted successfully",
    att_err_save:            "An error occurred",
    att_err_delete:          "Failed to delete record",
    att_on_leave_banner:         (name, until) => `${name} is currently on approved leave until ${until}. Recording is blocked.`,
    att_face_on_leave_blocked:   "This employee is currently on approved leave. Attendance cannot be recorded.",
    att_face_day_off_blocked:    "Today is a day off. Attendance cannot be recorded.",
    att_day_off_blocked:         "This day is set as a day off. Attendance cannot be recorded.",
    att_holiday_blocked:         (name) => `${name} is a public holiday. Attendance cannot be recorded.`,
    att_duplicate_blocked:       "Attendance is already recorded for this employee on this date.",
    att_after_hours_blocked:     "Check-in is not allowed after 18:00. This employee has been marked as Absent.",
    att_contract_inactive:       (name) => `${name}'s contract has expired and is Inactive. Attendance cannot be recorded.`,
    pay_contract_inactive:       (name) => `${name}'s contract has expired and is Inactive. Salary cannot be processed.`,
    // Attendance tabs
    att_tab_mgmt:         "Attendance Management",
    // Attendance Records
    rec_title:            "Attendance Records",
    rec_sub:              "Monthly attendance summary per employee",
    rec_col_present:      "Present Days",
    rec_col_absent:       "Absent Days",
    rec_col_late:         "Late Days",
    rec_col_leave:        "Leave Days",
    rec_col_rate:         "Rate",
    rec_stat_employees:   "Total Employees",
    rec_stat_avg:         "Avg. Attendance",
    // Working Days
    wd_title:             "Working Days",
    wd_sub:               "Set which days of the week are working days",
    wd_working:           "Working",
    wd_off:               "Day Off",
    wd_set_off:           "Set Off",
    wd_set_on:            "Set Working",
    wd_saved:             "Settings saved",
    wd_save_err:          "Failed to save",
    wd_working_days_count: "working days / week",
    wd_off_days_count:    "days off / week",
    // Holidays
    hol_title:            "Public Holidays",
    hol_sub:              "Set specific dates as holidays — attendance won't be counted",
    hol_add:              "Add Holiday",
    hol_name_label:       "Holiday Name",
    hol_date_label:       "Date",
    hol_name_ph:          "e.g., New Year",
    hol_no_holidays:      "No holidays added yet",
    hol_added:            "Holiday added",
    hol_deleted:          "Holiday removed",
    hol_add_err:          "Failed to add holiday",
    hol_del_err:          "Failed to remove holiday",
    hol_duplicate:        "A holiday already exists for this date",
    hol_badge:            "Holiday",
    hol_modal_info:       "Attendance is not counted on this day",
    hol_modal_emp:        "Employees on this day",
    // Sidebar nav
    nav_att_records:      "Attendance Records",
    nav_working_days:     "Working Days",
    nav_holidays:         "Holidays",
    // Contracts
    cont_title: "Contracts",
    cont_active_sub: (n) => `${n} active contracts`,
    cont_btn: "New Contract",
    cont_total: "Total",
    cont_active: "Active",
    cont_inactive: "Inactive",
    cont_on_leave: "On Leave",
    cont_suspended: "Suspended",
    cont_expired: "Expired",
    cont_col_start: "Start Date",
    cont_col_end: "End Date",
    cont_indefinite: "Indefinite",
    cont_modal_add: "New Contract",
    cont_modal_edit: "Edit Contract",
    cont_fld_type: "Contract Type *",
    cont_fld_start: "Start Date *",
    cont_fld_end: "End Date",
    cont_fld_salary: "Salary (IQD)",
    cont_btn_add: "Add Contract",
    cont_btn_update: "Update Contract",
    cont_expired_toast: (name) => `⚠️ ${name} — Contract has expired and set to Inactive`,
    // Documents
    docs_title: "Documents",
    docs_files_sub: (n) => `${n} files`,
    docs_btn: "Upload",
    docs_stat_total: "Total Files",
    docs_stat_pdf: "PDF Files",
    docs_stat_emp: "Employees",
    docs_stat_month: "This Month",
    docs_ph_search: "Search document",
    docs_all_emp: "All Employees",
    docs_col_doc: "Document",
    docs_col_size: "Size",
    docs_modal_add: "Upload Document",
    docs_modal_edit: "Edit Document",
    docs_drag_drop: "Drag & drop file here",
    docs_drag_click: "or click to browse — PDF, Word, Excel, Image",
    docs_fld_name: "Document Name *",
    docs_fld_type: "File Type",
    docs_fld_size: "File Size",
    docs_ph_name: "e.g. Employment Contract",
    docs_btn_upload: "Upload",
    docs_btn_update: "Update",
    // Expenses
    exp_title: "Expenses",
    exp_claims_sub: (n) => `${n} expense claims`,
    exp_btn: "New Expense",
    exp_stat_total: "Total Claims",
    exp_stat_approved: "Approved",
    exp_stat_pending: "Pending",
    exp_fld_category: "Category",
    exp_fld_amount: "Amount (IQD) *",
    exp_fld_desc: "Description",
    exp_ph_desc: "Expense description...",
    exp_col_category: "Category",
    exp_col_amount: "Amount",
    exp_col_desc: "Description",
    exp_modal_add: "New Expense",
    exp_modal_edit: "Edit Expense",
    exp_btn_add: "Add Expense",
    exp_btn_update: "Update Expense",
    exp_toast_add: "Expense added successfully",
    exp_toast_update: "Expense updated successfully",
    exp_toast_delete: "Expense deleted successfully",
    exp_toast_approved: "Expense approved",
    exp_toast_rejected: "Expense rejected",
    exp_toast_err: "An error occurred",
    exp_toast_err_upd: "Failed to update expense",
    exp_toast_err_del: "Failed to delete expense",
    exp_del_item: "expense",
    // Leave Requests
    leave_title: "Leave Requests",
    leave_sub: (n) => `${n} total requests`,
    leave_btn: "New Request",
    leave_stat_pending: "Pending",
    leave_stat_approved: "Approved",
    leave_stat_rejected: "Rejected",
    leave_col_start: "Start",
    leave_col_end: "End",
    leave_col_days: "Days",
    leave_fld_type: "Leave Type *",
    leave_fld_start: "Start Date *",
    leave_fld_end: "End Date *",
    leave_modal_add: "New Leave Request",
    leave_modal_edit: "Edit Request",
    leave_btn_add: "Add Request",
    leave_btn_update: "Update Request",
    // Payroll
    pay_title: "Payroll Management",
    pay_btn: "Add Payroll",
    pay_stat_total: "Total Payroll",
    pay_stat_paid: "Paid",
    pay_stat_pending: "Pending",
    pay_stat_deductions: "Deductions",
    pay_col_payment_date: "Payment Date",
    pay_col_base: "Base Salary",
    pay_col_bonus: "Bonus",
    pay_col_deductions: "Deductions",
    pay_col_net: "Net",
    pay_fld_payment_date: "Payment Date",
    pay_fld_base: "Base Salary *",
    pay_fld_bonus: "Bonus",
    pay_fld_deductions: "Deductions",
    pay_modal_add: "Add Payroll",
    pay_modal_edit: "Edit Payroll",
    pay_btn_mark: "Mark Paid",
    pay_btn_add: "Add Record",
    pay_btn_update: "Update Record",
    // Payroll tabs
    pay_tab_mgmt: "Payroll Management",
    pay_tab_salaries: "Employee Salaries",
    nav_emp_salaries: "Employee Salaries",
    // Employee Salaries page
    pay_sal_title: "Employee Salaries",
    pay_sal_sub: "Payroll history per employee",
    pay_sal_col_total_paid: "Total Paid",
    pay_sal_col_total_pending: "Total Pending",
    pay_sal_col_total_deduction: "Total Deduction",
    pay_sal_col_records: "Records",
    pay_sal_col_last_payment: "Last Payment",
    pay_sal_col_net_total: "Net Total",
    pay_sal_view: "View",
    pay_sal_payroll_history: "Payroll History",
    pay_sal_no_records: "No payroll records",
    pay_sal_not_received: "Not Received",
    // Requests
    req_title: "Requests",
    req_btn: "New Request",
    req_stat_pending: "Pending",
    req_stat_approved: "Approved",
    req_stat_rejected: "Rejected",
    req_col_subject: "Subject",
    req_col_submitted: "Submitted",
    req_fld_type: "Request Type",
    req_fld_subject: "Subject *",
    req_fld_date: "Submitted Date",
    req_ph_subject: "Request subject...",
    req_ph_notes: "Additional notes...",
    req_modal_add: "New Request",
    req_modal_edit: "Edit Request",
    req_btn_add: "Submit Request",
    req_btn_update: "Update Request",
    // Revenue
    rev_title: "Revenue",
    rev_btn: "Add Revenue",
    rev_stat_total: "Total Revenue",
    rev_stat_monthly: "This Month",
    rev_stat_topcat: "Top Category",
    rev_col_source: "Source",
    rev_col_category: "Category",
    rev_fld_source: "Source *",
    rev_fld_category: "Category",
    rev_fld_amount: "Amount (IQD) *",
    rev_fld_notes: "Notes",
    rev_ph_source: "Revenue source",
    rev_ph_notes: "Notes...",
    rev_modal_add: "Add Revenue",
    rev_modal_edit: "Edit Revenue",
    rev_btn_add: "Add Revenue",
    rev_btn_update: "Update Revenue",
    // Safe
    sav_title: "Safe",
    sav_btn: "New Goal",
    sav_stat_goals: "Total Goals",
    sav_stat_target: "Total Target",
    sav_stat_saved: "Total Expenditure",
    sav_stat_remaining: "Remaining",
    sav_fld_name: "Goal Name *",
    sav_fld_target: "Target Amount (IQD) *",
    sav_fld_saved: "Amount Expenditure (IQD)",
    sav_ph_name: "e.g. Emergency Fund",
    sav_saved_lbl: "Expenditure",
    sav_target_lbl: "Target",
    sav_remaining_lbl: "Remaining",
    sav_modal_add: "New Safe Goal",
    sav_modal_edit: "Edit Goal",
    sav_btn_add: "Add Goal",
    sav_btn_update: "Update Goal",
    sav_add_safe: "Add to Safe",
    sav_ph_add: "Amount to add (IQD)",
    // Employee Profile Panel
    prof_tab_info: "Info",
    prof_tab_attendance: "Attendance",
    prof_tab_leaves: "Leaves",
    prof_tab_docs: "Docs",
    prof_personal_details: "Personal Details",
    prof_emp_id: "Employee ID",
    prof_department: "Department",
    prof_position: "Position",
    prof_status: "Status",
    prof_email: "Email",
    prof_phone: "Phone",
    prof_gender: "Gender",
    prof_city: "City",
    prof_contract_salary: "Contract & Salary",
    prof_contract_type: "Contract Type",
    prof_hire_date: "Hire Date",
    prof_base_salary: "Base Salary",
    prof_biography: "Biography",
    prof_edit_profile: "Edit Profile",
    prof_change_password: "Change Password",
    prof_deactivate: "Deactivate",
    prof_month_summary: "This Month Summary",
    prof_days_present: "Days Present",
    prof_days_absent: "Days Absent",
    prof_days_late: "Days Late",
    prof_days_leave: "Days Leave",
    prof_todays_status: "Today's Status",
    prof_no_record: "No record",
    prof_check_in: "Check In",
    prof_check_out: "Check Out",
    prof_recent_records: "Recent Records",
    prof_leave_history: "Leave History",
    prof_no_leaves: "No leave records",
    prof_leave_lbl: "Leave",
    prof_days_lbl: "days",
    prof_emp_docs: "Employee Documents",
    prof_no_docs: "No documents uploaded",
    prof_dob: "Date of Birth",
    prof_work_hours: "Work Hours",
    prof_val_active: "Active",
    prof_val_inactive: "Inactive",
    prof_val_on_leave: "On Leave",
    prof_val_suspended: "Suspended",
    prof_val_early: "Early",
    prof_val_present: "Present",
    prof_val_absent: "Absent",
    prof_val_late: "Late",
    prof_val_approved: "Approved",
    prof_val_pending: "Pending",
    prof_val_rejected: "Rejected",
    prof_val_permanent: "Permanent",
    prof_val_temporary: "Temporary",
    prof_val_full_time: "Full-time",
    prof_val_part_time: "Part-time",
    prof_val_freelance: "Freelance",
    prof_val_expired: "Expired",
    prof_val_paid: "Paid",
    prof_val_failed: "Failed",
    // Employee toast messages
    emp_toast_add: "Employee added successfully",
    emp_toast_update: "Employee updated successfully",
    emp_toast_delete: "Employee deleted successfully",
    emp_toast_deactivated: (name) => `${name} deactivated`,
    emp_toast_err: "Something went wrong",
    emp_toast_err_add: "Failed to add employee",
    emp_toast_err_upd: "Failed to update employee",
    emp_toast_err_del: "Failed to delete employee",
    emp_toast_err_deactivate: "Failed to deactivate",
    // Contract toast messages
    cont_toast_add: "New contract added successfully",
    cont_toast_update: "Contract updated successfully",
    cont_toast_delete: "Contract deleted successfully",
    cont_toast_err: "Failed to save contract",
    cont_toast_err_del: "Failed to delete contract",
    // Leave request toast messages
    leave_toast_add: "Leave request added successfully",
    leave_toast_update: "Leave request updated successfully",
    leave_toast_delete: "Leave request deleted successfully",
    leave_toast_approved: "Leave approved",
    leave_toast_rejected: "Leave rejected",
    leave_toast_err: "An error occurred",
    leave_toast_err_upd: "Failed to update status",
    leave_toast_err_del: "Failed to delete",
    // Payroll toast messages
    pay_toast_add: "Payroll record added successfully",
    pay_toast_update: "Payroll updated successfully",
    pay_toast_delete: "Payroll record deleted successfully",
    pay_toast_paid: "Marked as paid",
    pay_toast_err: "An error occurred",
    pay_toast_err_upd: "Failed to update",
    pay_toast_err_del: "Failed to delete",
    // Safe toast messages
    sav_toast_add: "Savings goal added successfully",
    sav_toast_update: "Goal updated successfully",
    sav_toast_delete: "Goal deleted successfully",
    sav_toast_err: "An error occurred",
    sav_toast_err_upd: "Failed to update",
    sav_toast_err_del: "Failed to delete",
    // Documents toast messages
    docs_toast_add: "Document added successfully",
    docs_toast_update: "Document updated successfully",
    docs_toast_delete: "Document deleted successfully",
    docs_toast_err: "An error occurred",
    docs_toast_err_del: "Failed to delete",
    // Requests toast messages
    req_toast_add: "Request submitted successfully",
    req_toast_update: "Request updated successfully",
    req_toast_delete: "Request deleted successfully",
    req_toast_approved: "Request approved",
    req_toast_rejected: "Request rejected",
    req_toast_err: "An error occurred",
    req_toast_err_upd: "Failed to update",
    req_toast_err_del: "Failed to delete",
    // Revenue toast messages
    rev_toast_add: "Revenue added successfully",
    rev_toast_update: "Revenue updated successfully",
    rev_toast_delete: "Revenue deleted successfully",
    rev_toast_err: "An error occurred",
    rev_toast_err_del: "Failed to delete",
    // Delete dialog
    del_title: "Are you sure?",
    del_desc: (item) => `This will permanently delete this ${item}. This action cannot be undone.`,
    del_confirm: "Delete",
    // Requests page
    req_sub: "Employee requests inbox",
    req_type_transfer: "Transfer Request",
    req_type_salary: "Salary Review",
    req_type_equipment: "Equipment Request",
    req_type_remote: "Remote Work",
    req_type_training: "Training",
    req_type_other: "Other",
    // Revenue page
    rev_sub: (n) => `${n} revenue records`,
    rev_all_time: "All time",
    rev_transactions: "Transactions",
    rev_entries: "entries",
    rev_active_types: "active types",
    rev_monthly_trend: "Monthly Trend",
    rev_by_category: "By Category",
    rev_cat_sales: "Sales",
    rev_cat_services: "Services",
    rev_cat_projects: "Projects",
    rev_cat_other: "Other",
    // Safe page
    sav_goals_sub: (n) => n === 1 ? "1 safe goal" : `${n} safe goals`,
    sav_goal_details: "Goal Details",
    sav_started_date: "Started Date",
    sav_end_date: "End Date",
    sav_overall_progress: "Usage Rate",
    sav_started_lbl: "Started",
    sav_ends_lbl: "Ends",
    sav_no_goals: "No safe goals yet",
    // Leave types
    leave_type_annual: "Annual",
    leave_type_sick: "Sick",
    leave_type_unpaid: "Unpaid",
    leave_type_maternity: "Maternity",
    leave_type_paternity: "Paternity",
    leave_type_emergency: "Emergency",
    // Toast messages
    msg_saved: "Saved successfully",
    msg_updated: "Updated successfully",
    msg_deleted: "Deleted successfully",
    msg_error: "An error occurred",
    msg_error_delete: "Failed to delete",
    msg_error_update: "Failed to update",
    msg_error_deactivate: "Failed to deactivate",
    msg_marked_paid: "Marked as paid",
    msg_leave_status: (s) => `Leave ${s.toLowerCase()}`,
    msg_req_status: (s) => `Request ${s.toLowerCase()}`,
    msg_exp_status: (s) => `Expense ${s.toLowerCase()}`,
    // Profile & Theme
    nav_profile: "Profile",
    dark_mode: "Dark Mode",
    light_mode: "Light Mode",
    // Login / Logout
    login_title: "HR System",
    login_subtitle: "Sign in to your account",
    login_username: "Full Name",
    login_password: "Password",
    login_btn: "Sign In",
    login_hint: "Enter your full name exactly as registered in the system.",
    login_error: "Name not found or password is incorrect",
    logout_btn: "Log Out",
    prof_change_password_current: "Current Password",
    prof_change_password_new: "New Password",
    prof_change_password_confirm: "Confirm New Password",
    prof_change_password_required: "All fields are required",
    prof_change_password_mismatch: "Passwords do not match",
    prof_change_password_wrong: "Current password is incorrect",
    // Users page
    usr_title: "System Users",
    usr_sub: (n) => `${n} user${n !== 1 ? "s" : ""} total`,
    usr_add_btn: "Add User",
    usr_search_ph: "Search by name or email...",
    usr_col_joined: "Joined",
    usr_modal_add: "Add New User",
    usr_modal_edit: "Edit User",
    usr_section_info: "User Information",
    usr_fld_employee: "Select Employee",
    usr_ph_employee: "Choose an employee...",
    usr_fld_name: "Full Name *",
    usr_fld_email: "Email *",
    usr_fld_role: "Role *",
    usr_fld_pwd: "Password *",
    usr_fld_confirm_pwd: "Confirm Password *",
    usr_ph_pwd: "Min. 6 characters",
    usr_ph_confirm_pwd: "Re-enter password",
    usr_btn_add: "Add User",
    usr_btn_update: "Update User",
    usr_reset_title: "Reset Password",
    usr_fld_new_pwd: "New Password *",
    usr_fld_confirm_new_pwd: "Confirm New Password *",
    usr_ph_new_pwd: "Min. 6 characters",
    usr_ph_confirm_new_pwd: "Re-enter new password",
    usr_btn_reset: "Reset Password",
    usr_tooltip_reset: "Reset Password",
    usr_toast_emp_req: "Please select an employee",
    usr_toast_load_err: "Failed to load users",
    usr_toast_updated: "User updated successfully",
    usr_toast_added: "User added successfully",
    usr_toast_deleted: "User deleted successfully",
    usr_toast_delete_err: "Failed to delete user",
    usr_toast_pwd_req: "Password is required",
    usr_toast_pwd_mismatch: "Passwords do not match",
    usr_toast_pwd_short: "Password must be at least 6 characters",
    usr_toast_pwd_reset: "Password reset successfully",
    usr_toast_error: "Something went wrong",
    role_labels: {
      Admin: "Admin",
      "HR Manager": "HR Manager",
      Manager: "Manager",
      Viewer: "Viewer",
    },
    // Notifications
    notif_title: "Notifications",
    notif_empty: "No new notifications",
    notif_more: "more",
    lbl_pending: "Pending",
    // Settings page
    set_title: "Settings",
    set_sub: "Manage your application preferences",
    set_company_title: "Company Info",
    set_company_sub: "Company name and contact details",
    set_company_name: "Company Name",
    set_phone: "Phone",
    set_email: "Email",
    set_website: "Website",
    set_address: "Address",
    set_save_company: "Save Company Info",
    set_company_saved: "Company info saved!",
    set_appearance_title: "Appearance",
    set_appearance_sub: "Theme and language",
    set_theme: "Theme",
    set_theme_light: "☀️ Light",
    set_theme_dark: "🌙 Dark",
    set_language: "Language",
    set_pw_title: "Change Password",
    set_pw_sub: "Update your account password",
    set_current_pw: "Current Password",
    set_new_pw: "New Password",
    set_confirm_pw: "Confirm Password",
    set_change_pw_btn: "Change Password",
    set_pw_saving: "Saving...",
    set_pw_fill: "Please fill all fields",
    set_pw_no_match: "Passwords don't match",
    set_pw_short: "Password must be at least 6 characters",
    set_pw_changed: "Password changed!",
    set_db_title: "Database",
    set_db_sub: "Database management",
    set_db_btn: "Setup / Fix Database",
    set_db_working: "Working...",
    set_db_ready: "Database is ready!",
    set_db_error: "DB error",
    set_db_connect_error: "Cannot connect to database",
    set_db_hint: "If you need a new column or have a database issue, click this button",
    set_pwa_title: "Offline / PWA",
    set_pwa_sub: "Install on mobile — works without internet",
    set_pwa_installed: "✅ App installed successfully!",
    set_pwa_install_btn: "Install App (Offline Mode)",
    set_pwa_hint: "Once installed, works offline on mobile and laptop",
    set_pwa_chrome: "Open in Chrome and use 'Add to Home Screen'",
    set_pwa_done: "App installed!",
  },
  ku: {
    dir: "rtl",
    // Sidebar
    hr_system: "سیستەمی HR",
    emp_management: "بەڕێوەبردنی کارمەند",
    hr_role: "بەڕێوەبەری HR",
    // Nav
    nav_dashboard: "داشبۆرد",
    nav_employees: "کارمەندەکان",
    nav_contracts: "گرێبەستەکان",
    nav_expenses: "خەرجییەکان",
    nav_attendance: "ئامادەبوون",
    nav_leave_request: "داواکاری مۆڵەت",
    nav_payroll: "مووچەکان",
    nav_documents: "بەڵگەنامەکان",
    nav_requests: "داواکارییەکان",
    nav_revenue: "داهات",
    nav_savings: "سندوق",
    nav_users: "بەکارهێنەرانی سیستەم",
    nav_settings: "ڕێکخستنەکان",
    // Employee page
    emp_title: "کارمەندەکان",
    emp_total: (n) => `کۆی ${n} کارمەند`,
    emp_stat_all: "هەموو کارمەندەکان",
    emp_stat_active: "چالاک",
    emp_stat_inactive: "ناچالاک",
    emp_stat_on_leave: "مۆڵەت",
    emp_stat_suspended: "ئوقووفکراو",
    emp_add_btn: "زیادکردنی کارمەند",
    emp_search_placeholder: "گەڕان بە ناو یان ناسنامە...",
    emp_modal_add: "زیادکردنی کارمەند",
    emp_modal_edit: "دەستکاری کارمەند",
    // Sections
    emp_section_photo: "وێنەی پرۆفایل",
    emp_upload_photo: "بارکردنی وێنە",
    emp_upload_hint: "JPG، PNG یان GIF (زۆرترین: 800x800px)",
    emp_section_personal: "زانیاری کەسی",
    emp_section_employment: "وردەکاری کار",
    // Fields
    emp_full_name: "ناوی تەواو *",
    emp_phone: "ژمارەی تەلەفۆن *",
    emp_email: "ئیمەیل *",
    emp_gender: "ڕەگەز *",
    emp_male: "نێر",
    emp_female: "مێ",
    emp_city: "شار",
    emp_position: "پۆست *",
    emp_department: "بەش",
    emp_status: "دۆخ",
    emp_contract_type: "جۆری گرێبەست",
    emp_salary: "مووچەی بنەڕەت (دینار)",
    emp_hire_date: "بەرواری کارەکە",
    emp_bio: "بیۆگرافی / تێبینی",
    emp_bio_placeholder: "زانیاری زیاتر دەربارەی کارمەند...",
    emp_dob: "بەرواری لەدایکبوون",
    emp_work_start: "کاتژمێری دەستپێکردنی کار",
    emp_work_end: "کاتژمێری کۆتایی کار",
    ph_dob: "بەروار هەڵبژێرە",
    ph_work_time: "ب.م. ٠٩:٠٠",
    // Buttons
    btn_back: "گەڕانەوە",
    btn_cancel: "پاشگەزبوونەوە",
    btn_add: "زیادکردن",
    btn_update: "نوێکردنەوە",
    btn_profile: "پرۆفایل",
    btn_edit: "دەستکاری",
    btn_approve: "پەسەندکردن",
    btn_reject: "ڕەتکردنەوە",
    btn_print: "چاپکردن",
    // Table columns
    col_id: "ناسنامە",
    col_employee: "کارمەند",
    col_email: "ئیمەیل",
    col_position: "پۆست",
    col_department: "بەش",
    col_salary: "مووچە",
    col_status: "دۆخ",
    col_actions: "کردارەکان",
    col_date: "بەروار",
    col_type: "جۆر",
    col_notes: "تێبینی",
    // Placeholders
    ph_position: "پۆست هەڵبژێرە",
    ph_department: "بەش هەڵبژێرە",
    ph_status: "دۆخ هەڵبژێرە",
    ph_contract: "گرێبەست هەڵبژێرە",
    ph_city: "شار بنووسە",
    ph_name: "ناوی تەواو بنووسە",
    ph_phone: "ژمارەی تەلەفۆن بنووسە",
    ph_email: "ئیمەیل بنووسە",
    ph_notes_opt: "تێبینی (ئارەزووی)",
    // Language switcher
    lang_label: "زمان",
    // Common
    lbl_all: "هەموو",
    lbl_select_emp: "کارمەند هەڵبژێرە",
    lbl_required: "تکایە هەموو خانەکانی پێویست پڕ بکەرەوە",
    lbl_notes: "تێبینی",
    lbl_status: "دۆخ",
    lbl_date: "بەروار",
    lbl_employee: "کارمەند *",
    lbl_department: "بەش",
    lbl_no_data: "داتا نییە",
    dept_it: "IT",
    dept_finance: "دارایی",
    dept_hr: "HR",
    dept_marketing: "مارکتنگ",
    dept_operations: "کرداری",
    dept_design: "دیزاین",
    // Dashboard
    dash_title: "داشبۆرد",
    dash_sub: "بەخێربێیتەوە — ئەمەیە ئەوەی ئەمڕۆ ڕوودەدات.",
    dash_active_emp: "کارمەندە چالاکەکان",
    dash_total: (n) => `کۆی: ${n}`,
    dash_present_today: "ئامادەی ئەمڕۆ",
    dash_checked_in: "تۆماری کردووە",
    dash_pending_leaves: "مۆڵەتی چاوەڕوان",
    dash_awaiting: "چاوەڕوانی پەسەنددان",
    dash_unpaid_payroll: "مووچەی نەدراو",
    dash_emp_pending: "کارمەند چاوەڕوانە",
    dash_by_dept: "کارمەندان بەپێی بەش",
    dash_todays_att: "ئامادەبوونی ئەمڕۆ",
    dash_recent_leaves: "داواکاریی مۆڵەتی نوێ",
    dash_no_employees: "کارمەند نییە",
    dash_no_leaves: "داواکاری مۆڵەت نییە",
    dash_today_hours: "کاتژمێری کاری ئەمڕۆ",
    // Expenditure Analysis card
    ea_title: "شیکاری خەرجی",
    ea_sub: "ئامانجەکانی سەیف بەپێی کات",
    ea_weekly: "هەفتانە",
    ea_monthly: "مانگانە",
    ea_yearly: "ساڵانە",
    ea_stat_total: "کۆی داواکاریەکان",
    ea_stat_peak: "بەرزترین ماوە",
    // Attendance
    att_title: "ئامادەبوون",
    att_sub: "شوێنکردنی ئامادەبوونی رۆژانە",
    att_btn: "تۆمار",
    att_present: "ئامادە",
    att_absent: "نەبوو",
    att_late: "درەنگ",
    att_on_leave: "مۆڵەت",
    att_col_dept: "بەش",
    att_col_check_in: "کاتی هاتن",
    att_col_check_out: "کاتی ڕۆشتن",
    att_col_total_hours: "کۆی کاتژمێر",
    att_col_overtime: "کاتژمێری زیادە",
    att_modal_add: "زیادکردنی تۆمار",
    att_modal_edit: "دەستکاری تۆمار",
    att_fld_date: "بەروار *",
    att_fld_check_in: "کاتی هاتن",
    att_fld_check_out: "کاتی ڕۆشتن",
    att_fld_status: "دۆخ *",
    att_ph_notes: "تێبینی (ئارەزووی)",
    att_btn_add: "زیادکردنی تۆمار",
    att_btn_update: "نوێکردنەوەی تۆمار",
    // Face ID
    att_face_title_scan:     "🔍 Face ID — ئامادەبوون",
    att_face_title_register: "📷 تۆمارکردنی Face ID",
    att_face_steps_scan:     ["کامێرا کردنەوە", "دۆزینەوەی دەم", "گەڕانەوەی کارمەند", "تۆمارکردنی ئامادەبوون"],
    att_face_steps_reg:      ["کامێرا کردنەوە", "دۆزینەوەی دەم", "تۆمارکرا"],
    att_face_loading_init:   "دەستپێکردن...",
    att_face_loading_api:    "بارکردنی لایبرەری Face ID...",
    att_face_loading_models: "بارکردنی مۆدێلەکان (یەکەم جار ~٣٠چ)...",
    att_face_cam_ready:      "ڕووی خۆت بخەرە ناو فرەیمەکە",
    att_face_cam_retry:      (n) => `دووبارە هەوڵدەدرێت... (${n})`,
    att_face_detecting:      "دەمت دەدۆزرێتەوە...",
    att_face_matching:       "کارمەند دەگەڕێتەوە...",
    att_face_recording:      "ئامادەبوون تۆمار دەکرێت...",
    att_face_err_lib:        "لایبرەری face-api.js بار نەبوو.",
    att_face_err_models:     "مۆدێلەکان بار نەبوون.",
    att_face_err_camera:     "کامێرا نەدۆزرایەوە. مۆڵەتی کامێرا بدە.",
    att_face_err_scan:       "هەڵە لە سکان: ",
    att_face_err_reg:        "تۆمارکردن سەرکەوتوو نەبوو: ",
    att_face_err_match:      "گەڕانەوە سەرکەوتوو نەبوو: ",
    att_no_employee_found:   "هیچ کارمەندێک نەدۆزرایەوە بە ناوی",
    att_face_check_in:       "✅ هاتنەوە تۆمارکرا",
    att_face_check_out:      "🔵 ڕۆشتن تۆمارکرا",
    att_face_already:        "⚠️ ئەمڕۆ تۆمار تەواوبووە",
    att_face_days:           "روژی ئامادەبوون",
    att_face_reg_ok:         "Face ID بە سەرکەوتوویی تۆمارکرا!",
    att_face_done:           "تەواوبوو ✓",
    att_face_close:          "داخستن",
    att_face_sel_label:      "کارمەند هەڵبژێرە",
    att_face_sel_ph:         "کارمەند هەڵبژێرە...",
    att_face_scan_btn:       "📷 سکان و تۆمارکردنی Face ID",
    att_face_toast:          (name) => `Face ID تۆمارکرا بۆ ${name}`,
    att_face_warning:        "ڕووی خۆت ڕاستەوخۆ بەرامبەر کامێرا بگرە و دلنیابە نوری باشت هەیە.",
    att_face_btn_reg:        "تۆمارکردن",
    att_face_btn_scan:       "Face ID",
    att_toast_add:           "تۆماری ئامادەبوون زیادکرا",
    att_toast_update:        "تۆماری ئامادەبوون نوێکرایەوە",
    att_toast_delete:        "تۆمار سڕایەوە",
    att_err_save:            "هەڵەیەک ڕوویدا",
    att_err_delete:          "سڕینەوەی تۆمار سەرکەوتوو نەبوو",
    att_on_leave_banner:         (name, until) => `${name} ئێستا لە مۆڵەتی پەسەندکراودایە تا ${until}. تۆمارکردن ڕێ نادرێت.`,
    att_face_on_leave_blocked:   "ئەم کارمەندە ئێستا لە مۆڵەتی پەسەندکراودایە. تۆماری ئامادەبوون ناکرێت.",
    att_face_day_off_blocked:    "ئەمڕۆ رۆژی پشووە. تۆماری ئامادەبوون ناکرێت.",
    att_day_off_blocked:         "ئەم رۆژە وەک رۆژی پشوو دانراوە. تۆماری ئامادەبوون ناکرێت.",
    att_holiday_blocked:         (name) => `${name} جەژنی گشتیە. تۆماری ئامادەبوون ناکرێت.`,
    att_duplicate_blocked:       "تۆماری ئامادەبوون بۆ ئەم کارمەندە لەم رۆژەدا پێشتر تۆمارکراوە.",
    att_after_hours_blocked:     "دوای کاتژمێر ١٨:٠٠ دابنێین ڕێ نادرێت. ئەم کارمەندە وەک نەهاتوو تۆمار کراوە.",
    att_contract_inactive:       (name) => `کۆنتراکتی ${name} تەواو بووە و Inactive ە. تۆماری ئامادەبوون ناکرێت.`,
    pay_contract_inactive:       (name) => `کۆنتراکتی ${name} تەواو بووە و Inactive ە. مووچە ناکرێت بدرێت.`,
    // Attendance tabs
    att_tab_mgmt:         "بەڕێوەبردنی ئامادەبوون",
    // Attendance Records
    rec_title:            "تۆمارەکانی ئامادەبوون",
    rec_sub:              "پوختەی مانگانەی ئامادەبوون بۆ هەر کارمەندێک",
    rec_col_present:      "ڕۆژی ئامادە",
    rec_col_absent:       "ڕۆژی نەبوون",
    rec_col_late:         "ڕۆژی درەنگ",
    rec_col_leave:        "ڕۆژی مۆڵەت",
    rec_col_rate:         "ڕێژە",
    rec_stat_employees:   "کۆی کارمەندان",
    rec_stat_avg:         "ناوەندی ئامادەبوون",
    // Working Days
    wd_title:             "ڕۆژانی کار",
    wd_sub:               "دیاریکردنی ڕۆژانی کار لە هەفتادا",
    wd_working:           "کار",
    wd_off:               "پشووی کار",
    wd_set_off:           "ببەرە پشوو",
    wd_set_on:            "ببەرە کار",
    wd_saved:             "ڕێکخستنەکان پاشکەوتکرا",
    wd_save_err:          "پاشکەوتکردن سەرکەوتوو نەبوو",
    wd_working_days_count: "ڕۆژی کار لە هەفتادا",
    wd_off_days_count:    "ڕۆژی پشوو لە هەفتادا",
    // Holidays
    hol_title:            "پشووە فەرمیەکان",
    hol_sub:              "دیاریکردنی ڕۆژە تایبەتەکان وەک پشوو — ئامادەبوون هژمار نابێت",
    hol_add:              "زیادکردنی پشوو",
    hol_name_label:       "ناوی پشوو",
    hol_date_label:       "بەروار",
    hol_name_ph:          "بۆ نموونە: ساڵی نوێ",
    hol_no_holidays:      "هیچ پشوویەک زیاد نەکراوە",
    hol_added:            "پشوو زیادکرا",
    hol_deleted:          "پشوو سڕایەوە",
    hol_add_err:          "زیادکردن سەرکەوتوو نەبوو",
    hol_del_err:          "سڕینەوە سەرکەوتوو نەبوو",
    hol_duplicate:        "پشوویەک بۆ ئەم بەروارە پێشتر تۆمارکراوە",
    hol_badge:            "پشوو",
    hol_modal_info:       "ئامادەبوون بۆ ئەم رۆژە هژمار نابێت",
    hol_modal_emp:        "کارمەندان لەم رۆژەدا",
    // Sidebar nav
    nav_att_records:      "تۆمارەکانی ئامادەبوون",
    nav_working_days:     "ڕۆژانی کار",
    nav_holidays:         "پشووەکان",
    // Contracts
    cont_title: "گرێبەستەکان",
    cont_active_sub: (n) => `${n} گرێبەستی چالاک`,
    cont_btn: "گرێبەستی نوێ",
    cont_total: "کۆی گشتی",
    cont_active: "چالاک",
    cont_inactive: "ناچالاک",
    cont_on_leave: "مۆڵەت",
    cont_suspended: "ئوقووفکراو",
    cont_expired: "تەواوبوو",
    cont_col_start: "بەرواری دەستپێکردن",
    cont_col_end: "بەرواری کۆتایی",
    cont_indefinite: "بێ کۆتایی",
    cont_modal_add: "گرێبەستی نوێ",
    cont_modal_edit: "دەستکاری گرێبەست",
    cont_fld_type: "جۆری گرێبەست *",
    cont_fld_start: "بەرواری دەستپێکردن *",
    cont_fld_end: "بەرواری کۆتایی",
    cont_fld_salary: "مووچە (دینار)",
    cont_btn_add: "زیادکردنی گرێبەست",
    cont_btn_update: "نوێکردنەوەی گرێبەست",
    cont_expired_toast: (name) => `⚠️ ${name} — گرێبەست تەواو بووە و بووە ناچالاک`,
    // Documents
    docs_title: "بەڵگەنامەکان",
    docs_files_sub: (n) => `${n} فایل`,
    docs_btn: "بارکردن",
    docs_stat_total: "کۆی فایلەکان",
    docs_stat_pdf: "فایلی PDF",
    docs_stat_emp: "کارمەندەکان",
    docs_stat_month: "ئەم مانگە",
    docs_ph_search: "گەڕان بە بەڵگەنامە",
    docs_all_emp: "هەموو کارمەندەکان",
    docs_col_doc: "بەڵگەنامە",
    docs_col_size: "قەبارە",
    docs_modal_add: "بارکردنی بەڵگەنامە",
    docs_modal_edit: "دەستکاری بەڵگەنامە",
    docs_drag_drop: "فایل بکێشە و ڕەها بکە",
    docs_drag_click: "یان کلیک بکە بۆ گەڕان — PDF، Word، Excel، وێنە",
    docs_fld_name: "ناوی بەڵگەنامە *",
    docs_fld_type: "جۆری فایل",
    docs_fld_size: "قەبارەی فایل",
    docs_ph_name: "ب.م. گرێبەستی کار",
    docs_btn_upload: "بارکردن",
    docs_btn_update: "نوێکردنەوە",
    // Expenses
    exp_title: "خەرجییەکان",
    exp_claims_sub: (n) => `${n} داوای خەرجی`,
    exp_btn: "خەرجیی نوێ",
    exp_stat_total: "کۆی داواکان",
    exp_stat_approved: "پەسەندکراو",
    exp_stat_pending: "چاوەڕوان",
    exp_fld_category: "جۆر",
    exp_fld_amount: "بڕی پارە (دینار) *",
    exp_fld_desc: "وەسف",
    exp_ph_desc: "وەسفی خەرجی...",
    exp_col_category: "جۆر",
    exp_col_amount: "بڕ",
    exp_col_desc: "وەسف",
    exp_modal_add: "خەرجیی نوێ",
    exp_modal_edit: "دەستکاری خەرجی",
    exp_btn_add: "زیادکردنی خەرجی",
    exp_btn_update: "نوێکردنەوەی خەرجی",
    exp_toast_add: "خەرجی بە سەرکەوتوویی زیادکرا",
    exp_toast_update: "خەرجی بە سەرکەوتوویی نوێکرایەوە",
    exp_toast_delete: "خەرجی بە سەرکەوتوویی سڕایەوە",
    exp_toast_approved: "خەرجی پەسەندکرا",
    exp_toast_rejected: "خەرجی ڕەتکرایەوە",
    exp_toast_err: "هەڵەیەک ڕوویدا",
    exp_toast_err_upd: "نوێکردنەوەی خەرجی سەرکەوتوو نەبوو",
    exp_toast_err_del: "سڕینەوەی خەرجی سەرکەوتوو نەبوو",
    exp_del_item: "خەرجی",
    // Leave Requests
    leave_title: "داواکاریی مۆڵەت",
    leave_sub: (n) => `${n} داواکاری کۆی گشتی`,
    leave_btn: "داواکاری نوێ",
    leave_stat_pending: "چاوەڕوان",
    leave_stat_approved: "پەسەندکراو",
    leave_stat_rejected: "ڕەتکراو",
    leave_col_start: "دەستپێکردن",
    leave_col_end: "کۆتایی",
    leave_col_days: "ڕۆژ",
    leave_fld_type: "جۆری مۆڵەت *",
    leave_fld_start: "بەرواری دەستپێکردن *",
    leave_fld_end: "بەرواری کۆتایی *",
    leave_modal_add: "داواکاری مۆڵەتی نوێ",
    leave_modal_edit: "دەستکاری داواکاری",
    leave_btn_add: "زیادکردنی داواکاری",
    leave_btn_update: "نوێکردنەوەی داواکاری",
    // Payroll
    pay_title: "بەڕێوەبردنی مووچەکان",
    pay_btn: "زیادکردنی مووچە",
    pay_stat_total: "کۆی مووچەکان",
    pay_stat_paid: "دراو",
    pay_stat_pending: "چاوەڕوان",
    pay_stat_deductions: "کەمکردنەوەکان",
    pay_col_payment_date: "بەرواری پارەدان",
    pay_col_base: "مووچەی بنەڕەت",
    pay_col_bonus: "پاداشت",
    pay_col_deductions: "کەمکردنەوە",
    pay_col_net: "کۆی دیاری",
    pay_fld_payment_date: "بەرواری پارەدان",
    pay_fld_base: "مووچەی بنەڕەت *",
    pay_fld_bonus: "پاداشت",
    pay_fld_deductions: "کەمکردنەوە",
    pay_modal_add: "زیادکردنی مووچە",
    pay_modal_edit: "دەستکاری مووچە",
    pay_btn_mark: "وەک دراو نیشانبکە",
    pay_btn_add: "زیادکردنی تۆمار",
    pay_btn_update: "نوێکردنەوەی تۆمار",
    // Payroll tabs
    pay_tab_mgmt: "بەڕێوەبردنی مووچەکان",
    pay_tab_salaries: "مووچەی کارمەندان",
    nav_emp_salaries: "مووچەی کارمەندان",
    // Employee Salaries page
    pay_sal_title: "مووچەی کارمەندان",
    pay_sal_sub: "مێژووی مووچەکان بۆ هەر کارمەندێک",
    pay_sal_col_total_paid: "کۆی دراو",
    pay_sal_col_total_pending: "کۆی چاوەڕوان",
    pay_sal_col_total_deduction: "کۆی کەمکردنەوە",
    pay_sal_col_records: "تۆمارەکان",
    pay_sal_col_last_payment: "کۆتا پارەدان",
    pay_sal_col_net_total: "کۆی دیاری",
    pay_sal_view: "بینین",
    pay_sal_payroll_history: "مێژووی مووچە",
    pay_sal_no_records: "هیچ تۆماری مووچەیەک نییە",
    pay_sal_not_received: "نەدراوە",
    // Requests
    req_title: "داواکارییەکان",
    req_btn: "داواکاری نوێ",
    req_stat_pending: "چاوەڕوان",
    req_stat_approved: "پەسەندکراو",
    req_stat_rejected: "ڕەتکراو",
    req_col_subject: "بابەت",
    req_col_submitted: "داواکراو",
    req_fld_type: "جۆری داواکاری",
    req_fld_subject: "بابەت *",
    req_fld_date: "بەرواری داواکاری",
    req_ph_subject: "بابەتی داواکاری...",
    req_ph_notes: "تێبینی زیاتر...",
    req_modal_add: "داواکاری نوێ",
    req_modal_edit: "دەستکاری داواکاری",
    req_btn_add: "ناردنی داواکاری",
    req_btn_update: "نوێکردنەوەی داواکاری",
    // Revenue
    rev_title: "داهات",
    rev_btn: "زیادکردنی داهات",
    rev_stat_total: "کۆی داهات",
    rev_stat_monthly: "ئەم مانگە",
    rev_stat_topcat: "باشترین جۆر",
    rev_col_source: "سەرچاوە",
    rev_col_category: "جۆر",
    rev_fld_source: "سەرچاوە *",
    rev_fld_category: "جۆر",
    rev_fld_amount: "بڕی پارە (دینار) *",
    rev_fld_notes: "تێبینی",
    rev_ph_source: "سەرچاوەی داهات",
    rev_ph_notes: "تێبینی...",
    rev_modal_add: "زیادکردنی داهات",
    rev_modal_edit: "دەستکاری داهات",
    rev_btn_add: "زیادکردنی داهات",
    rev_btn_update: "نوێکردنەوەی داهات",
    // Safe
    sav_title: "سندوق",
    sav_btn: "ئامانجی نوێ",
    sav_stat_goals: "کۆی ئامانجەکان",
    sav_stat_target: "کۆی ئامانج",
    sav_stat_saved: "کۆی خەرجکراو",
    sav_stat_remaining: "ماوە",
    sav_fld_name: "ناوی ئامانج *",
    sav_fld_target: "بڕی ئامانج (دینار) *",
    sav_fld_saved: "بڕی خەرجکراو (دینار)",
    sav_ph_name: "ب.م. فەندی فریادرس",
    sav_saved_lbl: "خەرجکراو",
    sav_target_lbl: "ئامانج",
    sav_remaining_lbl: "ماوە",
    sav_modal_add: "ئامانجی سندوقی نوێ",
    sav_modal_edit: "دەستکاری ئامانج",
    sav_btn_add: "زیادکردنی ئامانج",
    sav_btn_update: "نوێکردنەوەی ئامانج",
    sav_add_safe: "زیادکردنی سندوق",
    sav_ph_add: "بڕی بەزیادکردن (دینار)",
    // Employee Profile Panel
    prof_tab_info: "زانیاری",
    prof_tab_attendance: "ئامادەبوون",
    prof_tab_leaves: "مۆڵەتەکان",
    prof_tab_docs: "بەڵگەنامە",
    prof_personal_details: "وردەکاری کەسی",
    prof_emp_id: "ناسنامەی کارمەند",
    prof_department: "بەش",
    prof_position: "پۆست",
    prof_status: "دۆخ",
    prof_email: "ئیمەیل",
    prof_phone: "تەلەفۆن",
    prof_gender: "ڕەگەز",
    prof_city: "شار",
    prof_contract_salary: "گرێبەست و مووچە",
    prof_contract_type: "جۆری گرێبەست",
    prof_hire_date: "بەرواری کارەکە",
    prof_base_salary: "مووچەی بنەڕەت",
    prof_biography: "بیۆگرافی",
    prof_edit_profile: "دەستکاری پرۆفایل",
    prof_change_password: "گۆڕینی وشەی نهێنی",
    prof_deactivate: "ناچالاككردن",
    prof_month_summary: "پوختەی ئەم مانگە",
    prof_days_present: "ڕۆژی ئامادە",
    prof_days_absent: "ڕۆژی نەبوون",
    prof_days_late: "ڕۆژی درەنگ",
    prof_days_leave: "ڕۆژی مۆڵەت",
    prof_todays_status: "دۆخی ئەمڕۆ",
    prof_no_record: "تۆمار نییە",
    prof_check_in: "کاتی هاتن",
    prof_check_out: "کاتی ڕۆشتن",
    prof_recent_records: "تۆمارە نوێکان",
    prof_leave_history: "مێژووی مۆڵەت",
    prof_no_leaves: "تۆماری مۆڵەت نییە",
    prof_leave_lbl: "مۆڵەت",
    prof_days_lbl: "ڕۆژ",
    prof_emp_docs: "بەڵگەنامەکانی کارمەند",
    prof_no_docs: "هیچ بەڵگەنامەیەک بارنەکراوە",
    prof_dob: "بەرواری لەدایکبوون",
    prof_work_hours: "کاتژمێری کار",
    prof_val_active: "چالاک",
    prof_val_inactive: "ناچالاک",
    prof_val_on_leave: "مۆڵەت",
    prof_val_suspended: "ئوقووفکراو",
    prof_val_early: "زوو",
    prof_val_present: "ئامادە",
    prof_val_absent: "نەبوو",
    prof_val_late: "درەنگ",
    prof_val_approved: "پەسەندکراو",
    prof_val_pending: "چاوەڕوان",
    prof_val_rejected: "ڕەتکراو",
    prof_val_permanent: "بە بردەوامی",
    prof_val_temporary: "کاتی",
    prof_val_full_time: "تەواو کات",
    prof_val_part_time: "نیوەی کات",
    prof_val_freelance: "فریلانسەر",
    prof_val_expired: "بەسەرچووی",
    prof_val_paid: "دراو",
    prof_val_failed: "سەرنەکەوتوو",
    // Employee toast messages
    emp_toast_add: "کارمەند بە سەرکەوتوویی زیادکرا",
    emp_toast_update: "کارمەند بە سەرکەوتوویی نوێکرایەوە",
    emp_toast_delete: "کارمەند بە سەرکەوتوویی سڕایەوە",
    emp_toast_deactivated: (name) => `${name} ناچالاككرا`,
    emp_toast_err: "هەڵەیەک ڕوویدا",
    emp_toast_err_add: "زیادکردنی کارمەند سەرکەوتوو نەبوو",
    emp_toast_err_upd: "نوێکردنەوەی کارمەند سەرکەوتوو نەبوو",
    emp_toast_err_del: "سڕینەوەی کارمەند سەرکەوتوو نەبوو",
    emp_toast_err_deactivate: "ناچالاككردن سەرکەوتوو نەبوو",
    // Contract toast messages
    cont_toast_add: "گرێبەستی نوێ بە سەرکەوتوویی زیادکرا",
    cont_toast_update: "گرێبەست بە سەرکەوتوویی نوێکرایەوە",
    cont_toast_delete: "گرێبەست بە سەرکەوتوویی سڕایەوە",
    cont_toast_err: "پاشکەوتکردنی گرێبەست سەرکەوتوو نەبوو",
    cont_toast_err_del: "سڕینەوەی گرێبەست سەرکەوتوو نەبوو",
    // Leave request toast messages
    leave_toast_add: "داواکاری مۆڵەت بە سەرکەوتوویی زیادکرا",
    leave_toast_update: "داواکاری مۆڵەت بە سەرکەوتوویی نوێکرایەوە",
    leave_toast_delete: "داواکاری مۆڵەت بە سەرکەوتوویی سڕایەوە",
    leave_toast_approved: "مۆڵەت پەسەندکرا",
    leave_toast_rejected: "مۆڵەت ڕەتکرایەوە",
    leave_toast_err: "هەڵەیەک ڕوویدا",
    leave_toast_err_upd: "نوێکردنەوەی دۆخ سەرکەوتوو نەبوو",
    leave_toast_err_del: "سڕینەوەی داواکاری سەرکەوتوو نەبوو",
    // Payroll toast messages
    pay_toast_add: "تۆماری مووچە بە سەرکەوتوویی زیادکرا",
    pay_toast_update: "مووچە بە سەرکەوتوویی نوێکرایەوە",
    pay_toast_delete: "تۆماری مووچە بە سەرکەوتوویی سڕایەوە",
    pay_toast_paid: "وەک دراو نیشانکرا",
    pay_toast_err: "هەڵەیەک ڕوویدا",
    pay_toast_err_upd: "نوێکردنەوە سەرکەوتوو نەبوو",
    pay_toast_err_del: "سڕینەوە سەرکەوتوو نەبوو",
    // Safe toast messages
    sav_toast_add: "ئامانجی سندوق بە سەرکەوتوویی زیادکرا",
    sav_toast_update: "ئامانج بە سەرکەوتوویی نوێکرایەوە",
    sav_toast_delete: "ئامانج بە سەرکەوتوویی سڕایەوە",
    sav_toast_err: "هەڵەیەک ڕوویدا",
    sav_toast_err_upd: "نوێکردنەوە سەرکەوتوو نەبوو",
    sav_toast_err_del: "سڕینەوە سەرکەوتوو نەبوو",
    // Documents toast messages
    docs_toast_add: "بەڵگەنامە بە سەرکەوتوویی زیادکرا",
    docs_toast_update: "بەڵگەنامە بە سەرکەوتوویی نوێکرایەوە",
    docs_toast_delete: "بەڵگەنامە بە سەرکەوتوویی سڕایەوە",
    docs_toast_err: "هەڵەیەک ڕوویدا",
    docs_toast_err_del: "سڕینەوەی بەڵگەنامە سەرکەوتوو نەبوو",
    // Requests toast messages
    req_toast_add: "داواکاری بە سەرکەوتوویی ناردرا",
    req_toast_update: "داواکاری بە سەرکەوتوویی نوێکرایەوە",
    req_toast_delete: "داواکاری بە سەرکەوتوویی سڕایەوە",
    req_toast_approved: "داواکاری پەسەندکرا",
    req_toast_rejected: "داواکاری ڕەتکرایەوە",
    req_toast_err: "هەڵەیەک ڕوویدا",
    req_toast_err_upd: "نوێکردنەوە سەرکەوتوو نەبوو",
    req_toast_err_del: "سڕینەوە سەرکەوتوو نەبوو",
    // Revenue toast messages
    rev_toast_add: "داهات بە سەرکەوتوویی زیادکرا",
    rev_toast_update: "داهات بە سەرکەوتوویی نوێکرایەوە",
    rev_toast_delete: "داهات بە سەرکەوتوویی سڕایەوە",
    rev_toast_err: "هەڵەیەک ڕوویدا",
    rev_toast_err_del: "سڕینەوەی داهات سەرکەوتوو نەبوو",
    // Delete dialog
    del_title: "دڵنیای؟",
    del_desc: (item) => `ئەمە ئەم ${item}ە بۆ هەمیشە دەسڕێتەوە. ئەم کردارە ناگەڕێتەوە.`,
    del_confirm: "سڕینەوە",
    // Requests page
    req_sub: "سندوقی داواکارییەکانی کارمەند",
    req_type_transfer: "داواکاری گواستنەوە",
    req_type_salary: "پێداچوونەوەی مووچە",
    req_type_equipment: "داواکاری ئامێر",
    req_type_remote: "کاری ئەرا دوور",
    req_type_training: "پەرەپێدان",
    req_type_other: "ئیتر",
    // Revenue page
    rev_sub: (n) => `${n} تۆماری داهات`,
    rev_all_time: "هەموو کات",
    rev_transactions: "مامەڵەکان",
    rev_entries: "تۆمار",
    rev_active_types: "جۆری چالاک",
    rev_monthly_trend: "ئاڕاستەی مانگانە",
    rev_by_category: "بەپێی جۆر",
    rev_cat_sales: "فرۆشتن",
    rev_cat_services: "خزمەتگوزاری",
    rev_cat_projects: "پرۆژەکان",
    rev_cat_other: "ئیتر",
    // Safe page
    sav_goals_sub: (n) => `${n} ئامانجی سندوق`,
    sav_goal_details: "وردەکاری ئامانج",
    sav_started_date: "بەرواری دەستپێکردن",
    sav_end_date: "بەرواری کۆتایی",
    sav_overall_progress: "ڕێژەی بەکارهێنراو",
    sav_started_lbl: "دەستپێکراوە",
    sav_ends_lbl: "کۆتایی دێت",
    sav_no_goals: "هیچ ئامانجی سندوق نییە",
  
    // Profile & Theme
    nav_profile: "پرۆفایل",
    dark_mode: "دۆخی تاریک",
    light_mode: "دۆخی ڕووناک",
    // Login / Logout
    login_title: "سیستەمی HR",
    login_subtitle: "بچۆ ناو سیستەمەکە",
    login_username: "ناوی تەواو",
    login_password: "وشەی نهێنی",
    login_btn: "چوونەژوورەوە",
    login_hint: "ناوی تەواوت بنووسە وەک چۆن لە سیستەمدا تۆمارکراوە.",
    login_error: "ناو نەدۆزرایەوە یان وشەی نهێنی هەڵەیە",
    logout_btn: "چوونەدەرەوە",
    prof_change_password_current: "وشەی نهێنی ئێستا",
    prof_change_password_new: "وشەی نهێنی نوێ",
    prof_change_password_confirm: "دووپاتکردنەوەی وشەی نهێنی نوێ",
    prof_change_password_required: "هەموو خانەکان پێویستن",
    prof_change_password_mismatch: "وشەکانی نهێنی یەکسان نین",
    prof_change_password_wrong: "وشەی نهێنی ئێستا هەڵەیە",
    // Users page
    usr_title: "بەکارهێنەرانی سیستەم",
    usr_sub: (n) => `کۆی ${n} بەکارهێنەر`,
    usr_add_btn: "زیادکردنی بەکارهێنەر",
    usr_search_ph: "گەڕان بە ناو یان ئیمەیل...",
    usr_col_joined: "بەرواری تۆمارکردن",
    usr_modal_add: "زیادکردنی بەکارهێنەری نوێ",
    usr_modal_edit: "دەستکاری بەکارهێنەر",
    usr_section_info: "زانیاری بەکارهێنەر",
    usr_fld_employee: "هەڵبژاردنی کارمەند",
    usr_ph_employee: "کارمەندێک هەڵبژێرە...",
    usr_fld_name: "ناوی تەواو *",
    usr_fld_email: "ئیمەیل *",
    usr_fld_role: "ڕۆڵ *",
    usr_fld_pwd: "وشەی نهێنی *",
    usr_fld_confirm_pwd: "دووپاتکردنەوەی وشەی نهێنی *",
    usr_ph_pwd: "کەمترین ٦ پیت",
    usr_ph_confirm_pwd: "دووبارە وشەی نهێنی بنووسە",
    usr_btn_add: "زیادکردنی بەکارهێنەر",
    usr_btn_update: "نوێکردنەوەی بەکارهێنەر",
    usr_reset_title: "ڕیسێتی وشەی نهێنی",
    usr_fld_new_pwd: "وشەی نهێنی نوێ *",
    usr_fld_confirm_new_pwd: "دووپاتکردنەوەی وشەی نهێنی نوێ *",
    usr_ph_new_pwd: "کەمترین ٦ پیت",
    usr_ph_confirm_new_pwd: "وشەی نهێنی نوێ دووبارە بنووسە",
    usr_btn_reset: "ڕیسێتی وشەی نهێنی",
    usr_tooltip_reset: "ڕیسێتی وشەی نهێنی",
    usr_toast_emp_req: "تکایە کارمەندێک هەڵبژێرە",
    usr_toast_load_err: "بارکردنی بەکارهێنەران سەرکەوتوو نەبوو",
    usr_toast_updated: "بەکارهێنەر بە سەرکەوتوویی نوێکرایەوە",
    usr_toast_added: "بەکارهێنەر بە سەرکەوتوویی زیادکرا",
    usr_toast_deleted: "بەکارهێنەر بە سەرکەوتوویی سڕایەوە",
    usr_toast_delete_err: "سڕینەوەی بەکارهێنەر سەرکەوتوو نەبوو",
    usr_toast_pwd_req: "وشەی نهێنی پێویستە",
    usr_toast_pwd_mismatch: "وشەکانی نهێنی یەکسان نین",
    usr_toast_pwd_short: "وشەی نهێنی دەبێت لانیکەم ٦ پیت بێت",
    usr_toast_pwd_reset: "وشەی نهێنی بە سەرکەوتوویی ڕیسێتکرا",
    usr_toast_error: "هەڵەیەک ڕوویدا",
    role_labels: {
      Admin: "ئەدمین",
      "HR Manager": "بەڕێوەبەری HR",
      Manager: "بەڕێوەبەر",
      Viewer: "بینەر",
    },
    // Notifications
    notif_title: "ئاگادارکردنەوەکان",
    notif_empty: "هیچ ئاگادارکردنەوەیەکی نوێ نییە",
    notif_more: "زیاتر",
    lbl_pending: "چاوەڕوان",
    // Settings page
    set_title: "ڕێکخستنەکان",
    set_sub: "بەڕێوەبردنی ئەرجەفەکانی ئەپەکەت",
    set_company_title: "زانیارییەکانی کۆمپانیا",
    set_company_sub: "ناوی کۆمپانیا و زانیارییەکانی پەیوەندی",
    set_company_name: "ناوی کۆمپانیا",
    set_phone: "ژمارەی مۆبایل",
    set_email: "ئیمەیل",
    set_website: "ماڵپەڕ",
    set_address: "ناونیشان",
    set_save_company: "پاشەکەوتکردنی زانیارییەکانی کۆمپانیا",
    set_company_saved: "زانیارییەکانی کۆمپانیا پاشەکەوت کرا!",
    set_appearance_title: "دیمەن",
    set_appearance_sub: "تیم و زمان",
    set_theme: "تیم",
    set_theme_light: "☀️ ڕووناک",
    set_theme_dark: "🌙 تاریک",
    set_language: "زمان",
    set_pw_title: "گۆڕینی پاسوۆرد",
    set_pw_sub: "نوێکردنەوەی پاسوۆردی ئەکاونتەکەت",
    set_current_pw: "پاسوۆردی ئێستا",
    set_new_pw: "پاسوۆردی نوێ",
    set_confirm_pw: "دووبارەکردنەوەی پاسوۆرد",
    set_change_pw_btn: "گۆڕینی پاسوۆرد",
    set_pw_saving: "پاشەکەوتدەکرێت...",
    set_pw_fill: "تکایە هەموو خانەکان پڕبکەوە",
    set_pw_no_match: "پاسوۆردەکان یەکسان نین",
    set_pw_short: "پاسوۆرد دەبێت لانیکەم ٦ پیت بێت",
    set_pw_changed: "پاسوۆرد گۆڕدرا!",
    set_db_title: "دیتابەیس",
    set_db_sub: "بەڕێوەبردنی دیتابەیس",
    set_db_btn: "دامەزراندن / چاکسازی دیتابەیس",
    set_db_working: "کاردەکات...",
    set_db_ready: "دیتابەیس ئامادەیە!",
    set_db_error: "کێشەی دیتابەیس",
    set_db_connect_error: "پەیوەندی بە دیتابەیس ناکرێت",
    set_db_hint: "ئەگەر خانەی نوێ پێویستت بوو یان کێشەی دیتابەیس هەبوو، ئەم بتنە بکە",
    set_pwa_title: "بەبێ ئینتەرنێت / PWA",
    set_pwa_sub: "دامەزراندن بە موبایل — بەبێ ئینتەرنێت",
    set_pwa_installed: "✅ بەسەرکەوتوویی دامەزراوە!",
    set_pwa_install_btn: "دامەزراندنی ئەپ (دۆخی ئۆفلاین)",
    set_pwa_hint: "کاتێک دامەزراند، بەبێ ئینتەرنێت لە موبایل و لاپتۆپ کاردەکات",
    set_pwa_chrome: "لە Chrome بکەرەوە و 'Add to Home Screen' بەکاربهێنە",
    set_pwa_done: "ئەپ دامەزراوە!",
  },
  ar: {
    dir: "rtl",
    // Sidebar
    hr_system: "نظام الموارد البشرية",
    emp_management: "إدارة الموظفين",
    hr_role: "مدير الموارد البشرية",
    // Nav
    nav_dashboard: "لوحة التحكم",
    nav_employees: "الموظفون",
    nav_contracts: "العقود",
    nav_expenses: "المصروفات",
    nav_attendance: "الحضور",
    nav_leave_request: "طلب إجازة",
    nav_payroll: "كشف الرواتب",
    nav_documents: "المستندات",
    nav_requests: "الطلبات",
    nav_revenue: "الإيرادات",
    nav_savings: "صندوق",
    nav_users: "مستخدمو النظام",
    nav_settings: "الإعدادات",
    // Employee page
    emp_title: "الموظفون",
    emp_total: (n) => `إجمالي ${n} موظف`,
    emp_stat_all: "جميع الموظفين",
    emp_stat_active: "نشط",
    emp_stat_inactive: "غير نشط",
    emp_stat_on_leave: "في إجازة",
    emp_stat_suspended: "موقوف",
    emp_add_btn: "إضافة موظف",
    emp_search_placeholder: "ابحث بالاسم أو المعرف...",
    emp_modal_add: "إضافة موظف",
    emp_modal_edit: "تعديل موظف",
    // Sections
    emp_section_photo: "صورة الملف الشخصي",
    emp_upload_photo: "رفع صورة",
    emp_upload_hint: "JPG أو PNG أو GIF (الحد الأقصى: 800x800px)",
    emp_section_personal: "المعلومات الشخصية",
    emp_section_employment: "تفاصيل التوظيف",
    // Fields
    emp_full_name: "الاسم الكامل *",
    emp_phone: "رقم الهاتف *",
    emp_email: "البريد الإلكتروني *",
    emp_gender: "الجنس *",
    emp_male: "ذكر",
    emp_female: "أنثى",
    emp_city: "المدينة",
    emp_position: "المنصب *",
    emp_department: "القسم",
    emp_status: "الحالة",
    emp_contract_type: "نوع العقد",
    emp_salary: "الراتب الأساسي (دينار)",
    emp_hire_date: "تاريخ التوظيف",
    emp_bio: "السيرة الذاتية / ملاحظات",
    emp_bio_placeholder: "معلومات إضافية عن الموظف...",
    emp_dob: "تاريخ الميلاد",
    emp_work_start: "وقت بدء العمل",
    emp_work_end: "وقت انتهاء العمل",
    ph_dob: "اختر التاريخ",
    ph_work_time: "مثال: 09:00",
    // Buttons
    btn_back: "رجوع",
    btn_cancel: "إلغاء",
    btn_add: "إضافة",
    btn_update: "تحديث",
    btn_profile: "الملف الشخصي",
    btn_edit: "تعديل",
    btn_approve: "موافقة",
    btn_reject: "رفض",
    btn_print: "طباعة",
    // Table columns
    col_id: "المعرف",
    col_employee: "الموظف",
    col_email: "البريد الإلكتروني",
    col_position: "المنصب",
    col_department: "القسم",
    col_salary: "الراتب",
    col_status: "الحالة",
    col_actions: "الإجراءات",
    col_date: "التاريخ",
    col_type: "النوع",
    col_notes: "ملاحظات",
    // Placeholders
    ph_position: "اختر المنصب",
    ph_department: "اختر القسم",
    ph_status: "اختر الحالة",
    ph_contract: "اختر العقد",
    ph_city: "أدخل المدينة",
    ph_name: "أدخل الاسم الكامل",
    ph_phone: "أدخل رقم الهاتف",
    ph_email: "أدخل البريد الإلكتروني",
    ph_notes_opt: "ملاحظات (اختياري)",
    // Language switcher
    lang_label: "اللغة",
    // Common
    lbl_all: "الكل",
    lbl_select_emp: "اختر الموظف",
    lbl_required: "يرجى ملء جميع الحقول المطلوبة",
    lbl_notes: "ملاحظات",
    lbl_status: "الحالة",
    lbl_date: "التاريخ",
    lbl_employee: "الموظف *",
    lbl_department: "القسم",
    lbl_no_data: "لا بيانات",
    dept_it: "تقنية المعلومات",
    dept_finance: "المالية",
    dept_hr: "الموارد البشرية",
    dept_marketing: "التسويق",
    dept_operations: "التشغيل",
    dept_design: "التصميم",
    // Dashboard
    dash_title: "لوحة التحكم",
    dash_sub: "مرحباً بعودتك — إليك ما يحدث اليوم.",
    dash_active_emp: "الموظفون النشطون",
    dash_total: (n) => `المجموع: ${n}`,
    dash_present_today: "الحضور اليوم",
    dash_checked_in: "قام بتسجيل الدخول",
    dash_pending_leaves: "الإجازات المعلقة",
    dash_awaiting: "في انتظار الموافقة",
    dash_unpaid_payroll: "الرواتب غير المدفوعة",
    dash_emp_pending: "موظف معلق",
    dash_by_dept: "الموظفون حسب القسم",
    dash_todays_att: "حضور اليوم",
    dash_recent_leaves: "طلبات الإجازات الأخيرة",
    dash_no_employees: "لا موظفين",
    dash_no_leaves: "لا طلبات إجازة",
    dash_today_hours: "ساعات العمل اليوم",
    // Expenditure Analysis card
    ea_title: "تحليل المصروفات",
    ea_sub: "أهداف الخزنة عبر الزمن",
    ea_weekly: "أسبوعي",
    ea_monthly: "شهري",
    ea_yearly: "سنوي",
    ea_stat_total: "إجمالي المطالبات",
    ea_stat_peak: "ذروة الإنفاق",
    // Attendance
    att_title: "الحضور",
    att_sub: "تتبع الحضور اليومي",
    att_btn: "تسجيل",
    att_present: "حاضر",
    att_absent: "غائب",
    att_late: "متأخر",
    att_on_leave: "في إجازة",
    att_col_dept: "القسم",
    att_col_check_in: "وقت الدخول",
    att_col_check_out: "وقت الخروج",
    att_col_total_hours: "إجمالي الساعات",
    att_col_overtime: "العمل الإضافي",
    att_modal_add: "إضافة سجل",
    att_modal_edit: "تعديل سجل",
    att_fld_date: "التاريخ *",
    att_fld_check_in: "وقت الدخول",
    att_fld_check_out: "وقت الخروج",
    att_fld_status: "الحالة *",
    att_ph_notes: "ملاحظات (اختياري)",
    att_btn_add: "إضافة سجل",
    att_btn_update: "تحديث السجل",
    // Face ID
    att_face_title_scan:     "🔍 Face ID — الحضور",
    att_face_title_register: "📷 تسجيل Face ID",
    att_face_steps_scan:     ["الكاميرا جاهزة", "مسح الوجه", "مطابقة الموظف", "تسجيل الحضور"],
    att_face_steps_reg:      ["الكاميرا جاهزة", "مسح الوجه", "تم التسجيل"],
    att_face_loading_init:   "جاري البدء...",
    att_face_loading_api:    "تحميل مكتبة Face ID...",
    att_face_loading_models: "تحميل النماذج (أول مرة ~٣٠ث)...",
    att_face_cam_ready:      "ضع وجهك داخل الإطار",
    att_face_cam_retry:      (n) => `إعادة المحاولة... (${n})`,
    att_face_detecting:      "جاري اكتشاف الوجه...",
    att_face_matching:       "جاري مطابقة الموظف...",
    att_face_recording:      "جاري تسجيل الحضور...",
    att_face_err_lib:        "فشل تحميل مكتبة face-api.js.",
    att_face_err_models:     "فشل تحميل النماذج.",
    att_face_err_camera:     "الكاميرا غير متوفرة. يرجى السماح بالوصول.",
    att_face_err_scan:       "خطأ في المسح: ",
    att_face_err_reg:        "فشل التسجيل: ",
    att_face_err_match:      "فشل المطابقة: ",
    att_no_employee_found:   "لم يتم العثور على موظف باسم",
    att_face_check_in:       "✅ تم تسجيل الحضور",
    att_face_check_out:      "🔵 تم تسجيل الانصراف",
    att_face_already:        "⚠️ تم التسجيل مسبقاً اليوم",
    att_face_days:           "يوم حضور",
    att_face_reg_ok:         "تم تسجيل Face ID بنجاح!",
    att_face_done:           "تم ✓",
    att_face_close:          "إغلاق",
    att_face_sel_label:      "اختر الموظف",
    att_face_sel_ph:         "اختر الموظف...",
    att_face_scan_btn:       "📷 مسح وتسجيل Face ID",
    att_face_toast:          (name) => `تم تسجيل Face ID لـ ${name}`,
    att_face_warning:        "ضع وجهك مباشرة أمام الكاميرا في إضاءة جيدة.",
    att_face_btn_reg:        "تسجيل",
    att_face_btn_scan:       "Face ID",
    att_toast_add:           "تمت إضافة سجل الحضور بنجاح",
    att_toast_update:        "تم تحديث سجل الحضور بنجاح",
    att_toast_delete:        "تم حذف السجل بنجاح",
    att_err_save:            "حدث خطأ",
    att_err_delete:          "فشل حذف السجل",
    att_on_leave_banner:         (name, until) => `${name} في إجازة معتمدة حتى ${until}. لا يمكن تسجيل الحضور.`,
    att_face_on_leave_blocked:   "هذا الموظف في إجازة معتمدة حالياً. لا يمكن تسجيل الحضور.",
    att_face_day_off_blocked:    "اليوم يوم إجازة. لا يمكن تسجيل الحضور.",
    att_day_off_blocked:         "هذا اليوم محدد كيوم إجازة. لا يمكن تسجيل الحضور.",
    att_holiday_blocked:         (name) => `${name} عطلة رسمية. لا يمكن تسجيل الحضور.`,
    att_duplicate_blocked:       "تم تسجيل الحضور مسبقاً لهذا الموظف في هذا التاريخ.",
    att_after_hours_blocked:     "لا يُسمح بتسجيل الدخول بعد الساعة 18:00. تم تسجيل هذا الموظف كغائب.",
    att_contract_inactive:       (name) => `عقد ${name} منتهٍ وغير نشط. لا يمكن تسجيل الحضور.`,
    pay_contract_inactive:       (name) => `عقد ${name} منتهٍ وغير نشط. لا يمكن صرف الراتب.`,
    // Attendance tabs
    att_tab_mgmt:         "إدارة الحضور",
    // Attendance Records
    rec_title:            "سجلات الحضور",
    rec_sub:              "ملخص شهري للحضور لكل موظف",
    rec_col_present:      "أيام الحضور",
    rec_col_absent:       "أيام الغياب",
    rec_col_late:         "أيام التأخير",
    rec_col_leave:        "أيام الإجازة",
    rec_col_rate:         "النسبة",
    rec_stat_employees:   "إجمالي الموظفين",
    rec_stat_avg:         "متوسط الحضور",
    // Working Days
    wd_title:             "أيام العمل",
    wd_sub:               "تحديد أيام العمل في الأسبوع",
    wd_working:           "يوم عمل",
    wd_off:               "يوم إجازة",
    wd_set_off:           "تعيين كإجازة",
    wd_set_on:            "تعيين كيوم عمل",
    wd_saved:             "تم حفظ الإعدادات",
    wd_save_err:          "فشل الحفظ",
    wd_working_days_count: "أيام عمل / أسبوع",
    wd_off_days_count:    "أيام إجازة / أسبوع",
    // Holidays
    hol_title:            "العطل الرسمية",
    hol_sub:              "تحديد تواريخ معينة كأعياد — لن يُحسب الحضور في هذه الأيام",
    hol_add:              "إضافة عطلة",
    hol_name_label:       "اسم العطلة",
    hol_date_label:       "التاريخ",
    hol_name_ph:          "مثال: رأس السنة",
    hol_no_holidays:      "لا توجد عطل مضافة بعد",
    hol_added:            "تمت إضافة العطلة",
    hol_deleted:          "تم حذف العطلة",
    hol_add_err:          "فشلت الإضافة",
    hol_del_err:          "فشل الحذف",
    hol_duplicate:        "يوجد عطلة لهذا التاريخ مسبقاً",
    hol_badge:            "عطلة",
    hol_modal_info:       "لا يُحسب الحضور في هذا اليوم",
    hol_modal_emp:        "الموظفون في هذا اليوم",
    // Sidebar nav
    nav_att_records:      "سجلات الحضور",
    nav_working_days:     "أيام العمل",
    nav_holidays:         "العطل",
    // Contracts
    cont_title: "العقود",
    cont_active_sub: (n) => `${n} عقد نشط`,
    cont_btn: "عقد جديد",
    cont_total: "المجموع",
    cont_active: "نشط",
    cont_inactive: "غير نشط",
    cont_on_leave: "في إجازة",
    cont_suspended: "موقوف",
    cont_expired: "منتهي",
    cont_col_start: "تاريخ البدء",
    cont_col_end: "تاريخ الانتهاء",
    cont_indefinite: "غير محدد",
    cont_modal_add: "عقد جديد",
    cont_modal_edit: "تعديل العقد",
    cont_fld_type: "نوع العقد *",
    cont_fld_start: "تاريخ البدء *",
    cont_fld_end: "تاريخ الانتهاء",
    cont_fld_salary: "الراتب (دينار)",
    cont_btn_add: "إضافة عقد",
    cont_btn_update: "تحديث العقد",
    cont_expired_toast: (name) => `⚠️ ${name} — انتهى العقد وأصبح غير نشط`,
    // Documents
    docs_title: "المستندات",
    docs_files_sub: (n) => `${n} ملف`,
    docs_btn: "رفع",
    docs_stat_total: "إجمالي الملفات",
    docs_stat_pdf: "ملفات PDF",
    docs_stat_emp: "الموظفون",
    docs_stat_month: "هذا الشهر",
    docs_ph_search: "ابحث عن المستند",
    docs_all_emp: "جميع الموظفين",
    docs_col_doc: "المستند",
    docs_col_size: "الحجم",
    docs_modal_add: "رفع مستند",
    docs_modal_edit: "تعديل المستند",
    docs_drag_drop: "اسحب وأفلت الملف هنا",
    docs_drag_click: "أو انقر للتصفح — PDF, Word, Excel, صورة",
    docs_fld_name: "اسم المستند *",
    docs_fld_type: "نوع الملف",
    docs_fld_size: "حجم الملف",
    docs_ph_name: "مثال: عقد عمل",
    docs_btn_upload: "رفع",
    docs_btn_update: "تحديث",
    // Expenses
    exp_title: "المصروفات",
    exp_claims_sub: (n) => `${n} طلب مصروف`,
    exp_btn: "مصروف جديد",
    exp_stat_total: "إجمالي المطالبات",
    exp_stat_approved: "مقبول",
    exp_stat_pending: "معلق",
    exp_fld_category: "الفئة",
    exp_fld_amount: "المبلغ (دينار) *",
    exp_fld_desc: "الوصف",
    exp_ph_desc: "وصف المصروف...",
    exp_col_category: "الفئة",
    exp_col_amount: "المبلغ",
    exp_col_desc: "الوصف",
    exp_modal_add: "مصروف جديد",
    exp_modal_edit: "تعديل المصروف",
    exp_btn_add: "إضافة مصروف",
    exp_btn_update: "تحديث المصروف",
    exp_toast_add: "تمت إضافة المصروف بنجاح",
    exp_toast_update: "تم تحديث المصروف بنجاح",
    exp_toast_delete: "تم حذف المصروف بنجاح",
    exp_toast_approved: "تمت الموافقة على المصروف",
    exp_toast_rejected: "تم رفض المصروف",
    exp_toast_err: "حدث خطأ",
    exp_toast_err_upd: "فشل تحديث المصروف",
    exp_toast_err_del: "فشل حذف المصروف",
    exp_del_item: "مصروف",
    // Leave Requests
    leave_title: "طلبات الإجازة",
    leave_sub: (n) => `${n} طلب إجمالي`,
    leave_btn: "طلب جديد",
    leave_stat_pending: "معلق",
    leave_stat_approved: "مقبول",
    leave_stat_rejected: "مرفوض",
    leave_col_start: "البدء",
    leave_col_end: "الانتهاء",
    leave_col_days: "الأيام",
    leave_fld_type: "نوع الإجازة *",
    leave_fld_start: "تاريخ البدء *",
    leave_fld_end: "تاريخ الانتهاء *",
    leave_modal_add: "طلب إجازة جديد",
    leave_modal_edit: "تعديل الطلب",
    leave_btn_add: "إضافة طلب",
    leave_btn_update: "تحديث الطلب",
    // Payroll
    pay_title: "إدارة الرواتب",
    pay_btn: "إضافة راتب",
    pay_stat_total: "إجمالي الرواتب",
    pay_stat_paid: "مدفوع",
    pay_stat_pending: "معلق",
    pay_stat_deductions: "الاستقطاعات",
    pay_col_payment_date: "تاريخ الدفع",
    pay_col_base: "الراتب الأساسي",
    pay_col_bonus: "المكافأة",
    pay_col_deductions: "الاستقطاعات",
    pay_col_net: "الصافي",
    pay_fld_payment_date: "تاريخ الدفع",
    pay_fld_base: "الراتب الأساسي *",
    pay_fld_bonus: "المكافأة",
    pay_fld_deductions: "الاستقطاعات",
    pay_modal_add: "إضافة راتب",
    pay_modal_edit: "تعديل الراتب",
    pay_btn_mark: "تحديد كمدفوع",
    pay_btn_add: "إضافة سجل",
    pay_btn_update: "تحديث السجل",
    // Payroll tabs
    pay_tab_mgmt: "إدارة الرواتب",
    pay_tab_salaries: "رواتب الموظفين",
    nav_emp_salaries: "رواتب الموظفين",
    // Employee Salaries page
    pay_sal_title: "رواتب الموظفين",
    pay_sal_sub: "سجل الرواتب لكل موظف",
    pay_sal_col_total_paid: "إجمالي المدفوع",
    pay_sal_col_total_pending: "إجمالي المعلق",
    pay_sal_col_total_deduction: "إجمالي الاستقطاعات",
    pay_sal_col_records: "السجلات",
    pay_sal_col_last_payment: "آخر دفعة",
    pay_sal_col_net_total: "صافي الإجمالي",
    pay_sal_view: "عرض",
    pay_sal_payroll_history: "سجل الرواتب",
    pay_sal_no_records: "لا توجد سجلات رواتب",
    pay_sal_not_received: "لم يُصرف",
    // Requests
    req_title: "الطلبات",
    req_btn: "طلب جديد",
    req_stat_pending: "معلق",
    req_stat_approved: "مقبول",
    req_stat_rejected: "مرفوض",
    req_col_subject: "الموضوع",
    req_col_submitted: "مقدم",
    req_fld_type: "نوع الطلب",
    req_fld_subject: "الموضوع *",
    req_fld_date: "تاريخ التقديم",
    req_ph_subject: "موضوع الطلب...",
    req_ph_notes: "ملاحظات إضافية...",
    req_modal_add: "طلب جديد",
    req_modal_edit: "تعديل الطلب",
    req_btn_add: "تقديم الطلب",
    req_btn_update: "تحديث الطلب",
    // Revenue
    rev_title: "الإيرادات",
    rev_btn: "إضافة إيراد",
    rev_stat_total: "إجمالي الإيرادات",
    rev_stat_monthly: "هذا الشهر",
    rev_stat_topcat: "أعلى فئة",
    rev_col_source: "المصدر",
    rev_col_category: "الفئة",
    rev_fld_source: "المصدر *",
    rev_fld_category: "الفئة",
    rev_fld_amount: "المبلغ (دينار) *",
    rev_fld_notes: "ملاحظات",
    rev_ph_source: "مصدر الإيراد",
    rev_ph_notes: "ملاحظات...",
    rev_modal_add: "إضافة إيراد",
    rev_modal_edit: "تعديل الإيراد",
    rev_btn_add: "إضافة إيراد",
    rev_btn_update: "تحديث الإيراد",
    // Safe
    sav_title: "صندوق",
    sav_btn: "هدف جديد",
    sav_stat_goals: "إجمالي الأهداف",
    sav_stat_target: "إجمالي الهدف",
    sav_stat_saved: "إجمالي المصروفات",
    sav_stat_remaining: "المتبقي",
    sav_fld_name: "اسم الهدف *",
    sav_fld_target: "المبلغ المستهدف (دينار) *",
    sav_fld_saved: "مبلغ المصروفات (دينار)",
    sav_ph_name: "مثال: صندوق طوارئ",
    sav_saved_lbl: "مصروف",
    sav_target_lbl: "الهدف",
    sav_remaining_lbl: "المتبقي",
    sav_modal_add: "هدف صندوق جديد",
    sav_modal_edit: "تعديل الهدف",
    sav_btn_add: "إضافة هدف",
    sav_btn_update: "تحديث الهدف",
    sav_add_safe: "إضافة للصندوق",
    sav_ph_add: "المبلغ المراد إضافته (دينار)",
    // Employee Profile Panel
    prof_tab_info: "معلومات",
    prof_tab_attendance: "الحضور",
    prof_tab_leaves: "الإجازات",
    prof_tab_docs: "المستندات",
    prof_personal_details: "البيانات الشخصية",
    prof_emp_id: "معرف الموظف",
    prof_department: "القسم",
    prof_position: "المنصب",
    prof_status: "الحالة",
    prof_email: "البريد الإلكتروني",
    prof_phone: "الهاتف",
    prof_gender: "الجنس",
    prof_city: "المدينة",
    prof_contract_salary: "العقد والراتب",
    prof_contract_type: "نوع العقد",
    prof_hire_date: "تاريخ التوظيف",
    prof_base_salary: "الراتب الأساسي",
    prof_biography: "السيرة الذاتية",
    prof_edit_profile: "تعديل الملف الشخصي",
    prof_change_password: "تغيير كلمة المرور",
    prof_deactivate: "إلغاء التفعيل",
    prof_month_summary: "ملخص هذا الشهر",
    prof_days_present: "أيام الحضور",
    prof_days_absent: "أيام الغياب",
    prof_days_late: "أيام التأخير",
    prof_days_leave: "أيام الإجازة",
    prof_todays_status: "حالة اليوم",
    prof_no_record: "لا يوجد سجل",
    prof_check_in: "وقت الحضور",
    prof_check_out: "وقت الانصراف",
    prof_recent_records: "السجلات الأخيرة",
    prof_leave_history: "سجل الإجازات",
    prof_no_leaves: "لا توجد سجلات إجازة",
    prof_leave_lbl: "إجازة",
    prof_days_lbl: "أيام",
    prof_emp_docs: "مستندات الموظف",
    prof_no_docs: "لم يتم رفع أي مستند",
    prof_dob: "تاريخ الميلاد",
    prof_work_hours: "ساعات العمل",
    prof_val_active: "نشط",
    prof_val_inactive: "غير نشط",
    prof_val_on_leave: "في إجازة",
    prof_val_suspended: "موقوف",
    prof_val_early: "مبكر",
    prof_val_present: "حاضر",
    prof_val_absent: "غائب",
    prof_val_late: "متأخر",
    prof_val_approved: "مقبول",
    prof_val_pending: "معلق",
    prof_val_rejected: "مرفوض",
    prof_val_permanent: "دائم",
    prof_val_temporary: "مؤقت",
    prof_val_full_time: "دوام كامل",
    prof_val_part_time: "دوام جزئي",
    prof_val_freelance: "مستقل",
    prof_val_expired: "منتهي",
    prof_val_paid: "مدفوع",
    prof_val_failed: "فاشل",
    // Employee toast messages
    emp_toast_add: "تمت إضافة الموظف بنجاح",
    emp_toast_update: "تم تحديث الموظف بنجاح",
    emp_toast_delete: "تم حذف الموظف بنجاح",
    emp_toast_deactivated: (name) => `تم تعطيل ${name}`,
    emp_toast_err: "حدث خطأ ما",
    emp_toast_err_add: "فشلت إضافة الموظف",
    emp_toast_err_upd: "فشل تحديث الموظف",
    emp_toast_err_del: "فشل حذف الموظف",
    emp_toast_err_deactivate: "فشل التعطيل",
    // Contract toast messages
    cont_toast_add: "تمت إضافة العقد الجديد بنجاح",
    cont_toast_update: "تم تحديث العقد بنجاح",
    cont_toast_delete: "تم حذف العقد بنجاح",
    cont_toast_err: "فشل حفظ العقد",
    cont_toast_err_del: "فشل حذف العقد",
    // Leave request toast messages
    leave_toast_add: "تمت إضافة طلب الإجازة بنجاح",
    leave_toast_update: "تم تحديث طلب الإجازة بنجاح",
    leave_toast_delete: "تم حذف طلب الإجازة بنجاح",
    leave_toast_approved: "تمت الموافقة على الإجازة",
    leave_toast_rejected: "تم رفض الإجازة",
    leave_toast_err: "حدث خطأ",
    leave_toast_err_upd: "فشل تحديث الحالة",
    leave_toast_err_del: "فشل الحذف",
    // Payroll toast messages
    pay_toast_add: "تمت إضافة سجل الراتب بنجاح",
    pay_toast_update: "تم تحديث الراتب بنجاح",
    pay_toast_delete: "تم حذف سجل الراتب بنجاح",
    pay_toast_paid: "تم التحديد كمدفوع",
    pay_toast_err: "حدث خطأ",
    pay_toast_err_upd: "فشل التحديث",
    pay_toast_err_del: "فشل الحذف",
    // Safe toast messages
    sav_toast_add: "تمت إضافة هدف الصندوق بنجاح",
    sav_toast_update: "تم تحديث الهدف بنجاح",
    sav_toast_delete: "تم حذف الهدف بنجاح",
    sav_toast_err: "حدث خطأ",
    sav_toast_err_upd: "فشل التحديث",
    sav_toast_err_del: "فشل الحذف",
    // Documents toast messages
    docs_toast_add: "تمت إضافة المستند بنجاح",
    docs_toast_update: "تم تحديث المستند بنجاح",
    docs_toast_delete: "تم حذف المستند بنجاح",
    docs_toast_err: "حدث خطأ",
    docs_toast_err_del: "فشل حذف المستند",
    // Requests toast messages
    req_toast_add: "تم تقديم الطلب بنجاح",
    req_toast_update: "تم تحديث الطلب بنجاح",
    req_toast_delete: "تم حذف الطلب بنجاح",
    req_toast_approved: "تمت الموافقة على الطلب",
    req_toast_rejected: "تم رفض الطلب",
    req_toast_err: "حدث خطأ",
    req_toast_err_upd: "فشل التحديث",
    req_toast_err_del: "فشل الحذف",
    // Revenue toast messages
    rev_toast_add: "تمت إضافة الإيراد بنجاح",
    rev_toast_update: "تم تحديث الإيراد بنجاح",
    rev_toast_delete: "تم حذف الإيراد بنجاح",
    rev_toast_err: "حدث خطأ",
    rev_toast_err_del: "فشل حذف الإيراد",
    // Delete dialog
    del_title: "هل أنت متأكد؟",
    del_desc: (item) => `سيؤدي هذا إلى حذف ${item} نهائياً. لا يمكن التراجع عن هذا الإجراء.`,
    del_confirm: "حذف",
    // Requests page
    req_sub: "صندوق طلبات الموظفين",
    req_type_transfer: "طلب نقل",
    req_type_salary: "مراجعة الراتب",
    req_type_equipment: "طلب معدات",
    req_type_remote: "العمل عن بُعد",
    req_type_training: "تدريب",
    req_type_other: "أخرى",
    // Revenue page
    rev_sub: (n) => `${n} سجل إيراد`,
    rev_all_time: "كل الأوقات",
    rev_transactions: "المعاملات",
    rev_entries: "سجل",
    rev_active_types: "أنواع نشطة",
    rev_monthly_trend: "الاتجاه الشهري",
    rev_by_category: "حسب الفئة",
    rev_cat_sales: "مبيعات",
    rev_cat_services: "خدمات",
    rev_cat_projects: "مشاريع",
    rev_cat_other: "أخرى",
    // Safe page
    sav_goals_sub: (n) => `${n} هدف صندوق`,
    sav_goal_details: "تفاصيل الهدف",
    sav_started_date: "تاريخ البدء",
    sav_end_date: "تاريخ الانتهاء",
    sav_overall_progress: "نسبة الاستخدام",
    sav_started_lbl: "بدأ",
    sav_ends_lbl: "ينتهي",
    sav_no_goals: "لا توجد أهداف صندوق بعد",
    
    nav_profile: "الملف الشخصي",
    dark_mode: "الوضع الداكن",
    light_mode: "الوضع الفاتح",
    // Login / Logout
    login_title: "نظام الموارد البشرية",
    login_subtitle: "سجّل دخولك إلى النظام",
    login_username: "الاسم الكامل",
    login_password: "كلمة المرور",
    login_btn: "تسجيل الدخول",
    login_hint: "أدخل اسمك الكامل كما هو مسجّل في النظام.",
    login_error: "الاسم غير موجود أو كلمة المرور غير صحيحة",
    logout_btn: "تسجيل الخروج",
    prof_change_password_current: "كلمة المرور الحالية",
    prof_change_password_new: "كلمة المرور الجديدة",
    prof_change_password_confirm: "تأكيد كلمة المرور الجديدة",
    prof_change_password_required: "جميع الحقول مطلوبة",
    prof_change_password_mismatch: "كلمتا المرور غير متطابقتين",
    prof_change_password_wrong: "كلمة المرور الحالية غير صحيحة",
    // Users page
    usr_title: "مستخدمو النظام",
    usr_sub: (n) => `إجمالي ${n} مستخدم`,
    usr_add_btn: "إضافة مستخدم",
    usr_search_ph: "ابحث بالاسم أو البريد الإلكتروني...",
    usr_col_joined: "تاريخ الانضمام",
    usr_modal_add: "إضافة مستخدم جديد",
    usr_modal_edit: "تعديل المستخدم",
    usr_section_info: "معلومات المستخدم",
    usr_fld_employee: "اختر موظفاً",
    usr_ph_employee: "اختر موظفاً...",
    usr_fld_name: "الاسم الكامل *",
    usr_fld_email: "البريد الإلكتروني *",
    usr_fld_role: "الدور *",
    usr_fld_pwd: "كلمة المرور *",
    usr_fld_confirm_pwd: "تأكيد كلمة المرور *",
    usr_ph_pwd: "٦ أحرف على الأقل",
    usr_ph_confirm_pwd: "أعد إدخال كلمة المرور",
    usr_btn_add: "إضافة مستخدم",
    usr_btn_update: "تحديث المستخدم",
    usr_reset_title: "إعادة تعيين كلمة المرور",
    usr_fld_new_pwd: "كلمة المرور الجديدة *",
    usr_fld_confirm_new_pwd: "تأكيد كلمة المرور الجديدة *",
    usr_ph_new_pwd: "٦ أحرف على الأقل",
    usr_ph_confirm_new_pwd: "أعد إدخال كلمة المرور الجديدة",
    usr_btn_reset: "إعادة تعيين كلمة المرور",
    usr_tooltip_reset: "إعادة تعيين كلمة المرور",
    usr_toast_emp_req: "يرجى اختيار موظف",
    usr_toast_load_err: "فشل تحميل المستخدمين",
    usr_toast_updated: "تم تحديث المستخدم بنجاح",
    usr_toast_added: "تمت إضافة المستخدم بنجاح",
    usr_toast_deleted: "تم حذف المستخدم بنجاح",
    usr_toast_delete_err: "فشل حذف المستخدم",
    usr_toast_pwd_req: "كلمة المرور مطلوبة",
    usr_toast_pwd_mismatch: "كلمتا المرور غير متطابقتين",
    usr_toast_pwd_short: "يجب أن تكون كلمة المرور ٦ أحرف على الأقل",
    usr_toast_pwd_reset: "تمت إعادة تعيين كلمة المرور بنجاح",
    usr_toast_error: "حدث خطأ",
    role_labels: {
      Admin: "مدير النظام",
      "HR Manager": "مدير الموارد البشرية",
      Manager: "مدير",
      Viewer: "مشاهد",
    },
    // Notifications
    notif_title: "الإشعارات",
    notif_empty: "لا توجد إشعارات جديدة",
    notif_more: "المزيد",
    lbl_pending: "قيد الانتظار",
    // Settings page
    set_title: "الإعدادات",
    set_sub: "إدارة تفضيلات التطبيق",
    set_company_title: "معلومات الشركة",
    set_company_sub: "اسم الشركة وبيانات الاتصال",
    set_company_name: "اسم الشركة",
    set_phone: "رقم الهاتف",
    set_email: "البريد الإلكتروني",
    set_website: "الموقع الإلكتروني",
    set_address: "العنوان",
    set_save_company: "حفظ معلومات الشركة",
    set_company_saved: "تم حفظ معلومات الشركة!",
    set_appearance_title: "المظهر",
    set_appearance_sub: "السمة واللغة",
    set_theme: "السمة",
    set_theme_light: "☀️ فاتح",
    set_theme_dark: "🌙 داكن",
    set_language: "اللغة",
    set_pw_title: "تغيير كلمة المرور",
    set_pw_sub: "تحديث كلمة مرور حسابك",
    set_current_pw: "كلمة المرور الحالية",
    set_new_pw: "كلمة المرور الجديدة",
    set_confirm_pw: "تأكيد كلمة المرور",
    set_change_pw_btn: "تغيير كلمة المرور",
    set_pw_saving: "جارٍ الحفظ...",
    set_pw_fill: "يرجى ملء جميع الحقول",
    set_pw_no_match: "كلمتا المرور غير متطابقتين",
    set_pw_short: "يجب أن تكون كلمة المرور ٦ أحرف على الأقل",
    set_pw_changed: "تم تغيير كلمة المرور!",
    set_db_title: "قاعدة البيانات",
    set_db_sub: "إدارة قاعدة البيانات",
    set_db_btn: "إعداد / إصلاح قاعدة البيانات",
    set_db_working: "جارٍ العمل...",
    set_db_ready: "قاعدة البيانات جاهزة!",
    set_db_error: "خطأ في قاعدة البيانات",
    set_db_connect_error: "لا يمكن الاتصال بقاعدة البيانات",
    set_db_hint: "إذا احتجت عموداً جديداً أو واجهت مشكلة في قاعدة البيانات، اضغط هذا الزر",
    set_pwa_title: "بدون إنترنت / PWA",
    set_pwa_sub: "التثبيت على الجوال — يعمل بدون إنترنت",
    set_pwa_installed: "✅ تم تثبيت التطبيق بنجاح!",
    set_pwa_install_btn: "تثبيت التطبيق (وضع عدم الاتصال)",
    set_pwa_hint: "بعد التثبيت، يعمل بدون إنترنت على الجوال والحاسوب",
    set_pwa_chrome: "افتحه في Chrome واستخدم 'إضافة إلى الشاشة الرئيسية'",
    set_pwa_done: "تم تثبيت التطبيق!",
  },
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState("en");

  useEffect(() => {
    const saved = localStorage.getItem("app-lang");
    if (saved && translations[saved]) {
      setLang(saved);
      document.documentElement.dir = translations[saved].dir;
      document.documentElement.lang = saved;
    }
  }, []);

  const switchLang = (l) => {
    if (!translations[l]) return;
    setLang(l);
    localStorage.setItem("app-lang", l);
    document.documentElement.dir = translations[l].dir;
    document.documentElement.lang = l;
  };

  const t = translations[lang];

  const VALUE_MAP = {
    "Active":    t.prof_val_active,
    "Inactive":  t.prof_val_inactive,
    "On Leave":  t.prof_val_on_leave,
    "Suspended": t.prof_val_suspended,
    "Early":     t.prof_val_early,
    "Present":   t.prof_val_present,
    "Absent":    t.prof_val_absent,
    "Late":      t.prof_val_late,
    "Approved":  t.prof_val_approved,
    "Pending":   t.prof_val_pending,
    "Rejected":  t.prof_val_rejected,
    "Permanent": t.prof_val_permanent,
    "Temporary": t.prof_val_temporary,
    "Full-time": t.prof_val_full_time,
    "Part-time": t.prof_val_part_time,
    "Freelance": t.prof_val_freelance,
    "Expired":   t.prof_val_expired,
    "Paid":      t.prof_val_paid,
    "Failed":    t.prof_val_failed,
    // Revenue categories
    "Sales":             t.rev_cat_sales,
    "Services":          t.rev_cat_services,
    "Projects":          t.rev_cat_projects,
    "Other":             t.rev_cat_other,
    // Request types
    "Transfer Request":  t.req_type_transfer,
    "Salary Review":     t.req_type_salary,
    "Equipment Request": t.req_type_equipment,
    "Remote Work":       t.req_type_remote,
    "Training":          t.req_type_training,
    // Departments
    "IT":         t.dept_it,
    "Finance":    t.dept_finance,
    "HR":         t.dept_hr,
    "Marketing":  t.dept_marketing,
    "Operations": t.dept_operations,
    "Design":     t.dept_design,
  };
  const tv = (val) => VALUE_MAP[val] || val;

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t, tv }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
